# Coluna cervical
ENTRADAS = [
    ("#", "COLUNA CERVICAL"),

    # ---- alinhamento e corpos vertebrais ----
    ("corposcervnl1", "Corpos vertebrais cervicais alinhados", "1636"),
    ("retificacerv1", "Retificação da curvatura cervical", "1639"),
    ("retificacerv3", "Retificação da lordose cervical na posição do exame", "1696"),
    ("retificacerv4", "TC — retificação da curvatura com tendência à inversão", "9362"),
    ("lordosecerv1", "Acentuação / retificação da lordose cervical em decúbito", "1801"),
    ("lordosecerv2", "TC — leve acentuação da lordose cervical em decúbito", "9363"),
    ("retrolistecerv1", "Discreta retrolistese de C5 sobre C6", "1695"),
    ("listesecerv1", "Mínima retrolistese / anterolistese cervical", "1797"),
    ("anterolistecerv1", "TC — anterolistese de C4 sobre C5 (grau I)", "9354"),
    ("tonsilas1", "Insinuação das tonsilas cerebelares pelo forame magno", "1794"),
    ("osteofitoscerv1", "Osteófitos marginais difusos", "1699"),
    ("osteofitoscerv2", "Reação osteofitária marginal dos corpos vertebrais cervicais", "1700"),
    ("osteofitoscerv3", "TC — osteófitos marginais anteriores e posteriores", "9366"),
    ("hemangiomacerv1", "Hemangiomas nos corpos vertebrais de C6, C7 e T1", "1707"),
    ("infiltracaomed1", "Infiltração da medular óssea por lesões secundárias", "1703"),
    ("medularinesp1", "Alteração difusa do sinal da medular óssea, inespecífica", "1776"),

    # ---- discos e platôs ----
    ("discoscervnl1", "Discos intervertebrais cervicais com morfologia e sinal preservados", "1642"),
    ("desidratacerv1", "Desidratação discal cervical com redução da altura", "1720"),
    ("desidratacerv2", "Desidratação discal com Modic I e II", "1723"),
    ("modiccerv1", "Degeneração gordurosa das placas terminais (Modic II)", "1809"),
    ("modiccerv2", "Degeneração edematosa/gordurosa (Modic I/II) com Schmorl", "1810"),
    ("reducaodiscocerv1", "TC — redução difusa da altura dos interespaços cervicais", "9414"),
    ("reducaodiscocerv2", "TC — leve redução da altura em C3-C4 e C4-C5", "9415"),

    # ---- uncovertebrais e interfacetárias ----
    ("uncoart1", "Hipertrofia degenerativa uncovertebral com redução foraminal", "410", "bullet"),
    ("uncoart2", "Uncoartrose bilateral de C4-C5 a C6-C7", "1713"),
    ("uncoart3", "Hipertrofia das unciformes com redução das amplitudes foraminais", "1736"),
    ("uncoart4", "Hipertrofia do processo unciforme com uncoartrose", "1821"),
    ("uncoart5", "Uncoartrose bilateral de C3-C4 a C6-C7", "1822"),
    ("uncoart6", "TC — hipertrofia dos processos unciformes em C4-C5", "9389"),
    ("uncoart7", "TC — artrose uncovertebral de C3-C4 e C4-C5", "9390"),
    ("uncoart8", "TC — artrose uncovertebral de C4-C5 a C6-C7", "9391"),
    ("uncoart9", "Uncoartrose de C3-C4 a C6-C7 com contato radicular", "12496"),
    ("interfacetcerv1", "Leve alteração degenerativa difusa das interfacetárias", "1710"),
    ("interfacetcerv5", "Alteração degenerativa difusa das interfacetárias", "1825"),
    ("interfacetcerv2", "Processo inflamatório osteo-hipertrófico da interfacetária", "1826-1827", "unir"),
    ("artrointerfacet1", "TC — artrose difusa das interfacetárias cervicais", "9383"),
    ("artrointerfacet2", "TC — artrose interfacetária de C3-C4 a C6-C7", "9384"),
    ("fusaointerfacet1", "TC — fusão da interfacetária de C4-C5", "9382"),
    ("atlantoaxial1", "Alteração degenerativa da articulação atlantoaxial", "1840"),
    ("atlantodental1", "Alteração degenerativa da articulação atlantodental média", "1841"),
    ("atlantodental2", "TC — alteração degenerativa atlantodental com esclerose", "9379"),
    ("ligamarelocerv1", "Espessamento dos ligamentos amarelos em C5-C6 e C6-C7", "1850"),
    ("ligamarelocerv2", "TC — espessamento dos ligamentos amarelos em C5 e C6", "9407"),
    ("calcalar1", "TC — calcificação na topografia do ligamento alar", "9369"),
    ("calcllant1", "TC — calcificação do ligamento longitudinal anterior", "9376"),
    ("calcnucal1", "TC — calcificação na topografia do ligamento nucal", "9399"),

    # ---- discopatias por nível ----
    ("abaulcerv1", "Abaulamento discal posterior moldando o saco dural", "1739"),
    ("abaulcerv2", "Leve abaulamento discal sem outras repercussões", "1742"),
    ("abaulcerv3", "Complexo disco-osteofitário com redução foraminal", "1745"),
    ("abaulcerv4", "Abaulamento paramediano à direita com contato radicular", "1748"),
    ("abaulcerv5", "Abaulamento disco-osteofitário com uncoartrose, sem contatos", "1751"),
    ("abaulcerv6", "C3-C4 — componente protruso com rotura do anel fibroso", "1871"),
    ("abaulcerv7", "C4-C5 — disco-osteofitário com uncoartrose e redução foraminal", "1874"),
    ("abaulcerv8", "C6-C7 — protrusão disco-osteofitária foraminal esquerda", "1877"),
    ("abaulcerv9", "Abaulamento com protrusão paramediana à direita", "1880"),
    ("abaulcerv10", "C3-C4 — abaulamento com uncoartrose e interfacetárias", "1883"),
    ("abaulcerv11", "C3-C4 — pequena protrusão discal posterior mediana", "1894"),
    ("abaulcerv12", "C4-C5 — saliência posterior de fibras do anel fibroso", "1897"),
    ("abaulcerv13", "C4-C5 — disco-osteofitário com compressão da raiz foraminal", "1900"),
    ("abaulcerv14", "C5-C6 — protruso póstero-central tocando a medula", "1907"),
    ("abaulcerv15", "C5-C6 — protruso póstero-lateral esquerdo com compressão medular", "1912"),
    ("abaulcerv16", "C5-C6 — componente extruso com migração caudal", "1917"),
    ("abaulcerv17", "C6-C7 — protruso póstero-lateral esquerdo", "1932"),
    ("abaulcerv18", "C6-C7 — protruso póstero-central tocando a medula", "1939"),
    ("abaulcerv19", "C7-T1 — abaulamento disco-osteofitário posterior", "1950"),
    ("abaulcerv20", "C7-T1 — disco-osteofitário com anterolistese", "1957"),
    ("abaulcerv21", "C7-T1 — protrusão discal posterior mediana", "1964"),
    ("abaulcerv22", "C4-C5 — protrusão discal posterior central", "12313"),
    ("abaulcerv23", "C5-C6 — protrusão centrolateral direita com fissura do ânulo", "12314"),
    ("abaulcerv30", "C6-C7 — protrusão discal posterior central (linha truncada na fonte)", "12315"),
    ("abaulcerv24", "C6-C7 — protrusão com impressão medular e da raiz emergente", "12502"),
    ("abaulcervtc1", "TC — pequeno abaulamento disco-osteofitário posterior", "9432", "bullet"),
    ("abaulcervtc2", "TC — pequena protrusão disco-osteofitária posterior", "9433"),
    ("abaulcervtc3", "TC — protrusão posterior mediana/paramediana", "9434", "bullet"),
    ("abaulcervtc4", "TC — disco-osteofitário com estenose foraminal", "9435", "bullet"),
    ("abaulcervtc5", "TC — disco-osteofitário póstero-central e paramediano", "9436", "bullet"),
    ("abaulcervtc6", "TC — componente extruso com migração cranial", "9437", "bullet"),
    ("estenosecerv1", "Redução do calibre do canal medular de C3 a C6", "1758"),

    # ---- medula, conclusões e pós-operatório ----
    ("mielomalacia1", "Redução do calibre medular de aspecto sequelar (mielomalácia)", "2009"),
    ("mielomalacia2", "Mielomalácia cicatricial dos cornos anteriores em C5-C6", "11593", "bullet"),
    ("espondilosecerv1", "Espondilose cervical moderada", "1779"),
    ("discopatiacerv1", "Discopatia multissegmentar com contato radicular", "1782"),
    ("discopatiacerv2", "Discopatia degenerativa multissegmentar", "1996"),
    ("discopatiacerv3", "Discopatia multissegmentar com estreitamento do canal", "1997"),
    ("discopatiacerv4", "Conclusão — discopatia com conflito radicular em C6-C7", "12510"),
    ("longuscolli1", "Tendinopatia calcária da origem do longus colli", "401"),
    ("lipomacerv1", "Lesão lipomatosa subcutânea junto ao trapézio", "1984"),
    ("espacadorcerv1", "Espaçador intersomático com parafusos intrassomáticos", "2012"),
    ("espacadorcerv2", "Espaçadores intersomáticos em C5-C6 e C6-C7", "2015"),
    ("artrodesecerv1", "Artrodese cervical via posterior com hastes e parafusos", "9485"),
    ("artrodesecerv2", "Artrodese de C5-C6 com espaçador discal anterior", "11581", "bullet"),
    ("corpectomia1", "Corpectomia parcial com prótese vertebral", "916"),
    ("enfisemacervical1", "Densificação cervical com focos de enfisema pós-cirúrgico", "917"),
    ("poscirurgcerv1", "Conclusão — controle pós-cirúrgico da coluna cervical", "2073"),
    ("poscirurgcerv2", "Comparação — cirurgia em C5-C6 com resolução da extrusão", "12306"),
    ("poscirurgcerv3", "Conclusão — artrodese anterior com prótese vertebral", "930"),
    ("obscerv1", "Obs. — discopatia de T2-T3 vista apenas nas sagitais", "2094"),

    ("abaulcerv25", "Abaulamento com hipertrofia uncovertebral e redução foraminal", "234"),

    ("desidratacerv3", "Desidratação discal cervical com redução em C5-C6, C6-C7 e C7-T1", "1864"),
    ("interfacetcerv3", "Lâmina líquida na interfacetária de C7-D1", "12503", "bullet"),
    ("desidratacerv4", "Leve desidratação discal multissegmentar", "12501", "bullet"),
    ("medulacervnl1", "Medula espinhal preservada", "12505", "bullet"),
    # ---- laudos completos ----
    ("rmcervical2", "RM de coluna cervical — normal com retificação", "1616-1665"),
    ("rmcervical3", "RM de coluna cervical — modelo mestre", "1674-1782 !1677"),
    ("rmcervical4", "RM de coluna cervical — pós-operatório com espaçadores", "2008-2094"),
    ("rmcervical5", "RM de coluna cervical — artrodese com mielomalácia", "11575-11598"),
    ("tccervical", "TC de coluna cervical — espondilose com discopatia", "9262-9336"),
    ("tccervical2", "TC de coluna cervical — pós-operatório com corpectomia", "904-930"),
    ("tccervical3", "TC de coluna cervical — modelo mestre com alternativas", "9343-9478 !9353,9355,9431"),
]
