# Cotovelo
ENTRADAS = [
    ("#", "COTOVELO"),

    # ---- epicôndilo lateral / extensores ----
    ("epicondlat1", "Epicondilite lateral com fissuras intrassubstanciais", "1099", "bullet"),
    ("epicondlat2", "Leve tendinopatia da origem comum dos extensores", "1102", "bullet"),
    ("epicondlat3", "Tendinopatia dos extensores com rotura parcial de 50%", "1107", "bullet"),
    ("epicondlat4", "Tendinopatia dos extensores com fissuras, sem transfixações", "1244"),
    ("epicondlat5", "Conclusão — tendinopatia dos extensores com rotura parcial", "1202"),
    ("epicondlat6", "Conclusão — tendinopatia dos extensores sem transfixações", "1357"),
    ("epicondlat7", "Peritendinite reacional dos extensores e flexores", "1408"),
    ("epicondlat8", "Leve tendinopatia na origem comum dos extensores", "11773"),

    # ---- epicôndilo medial / flexores ----
    ("epicondmed1", "Discreta peritendinite da origem comum dos flexores", "1112", "bullet"),
    ("epicondmed2", "Tendinopatia da origem comum dos flexores, sem roturas", "1247"),
    ("epicondmed3", "Conclusão — peritendinite dos flexores no epicôndilo medial", "1205"),
    ("epicondmed4", "Tendinopatia dos flexores com delaminações intrassubstanciais", "694", "bullet"),
    ("epicondmed5", "Tendinopatia com peritendinite dos flexores com fissuras", "11772"),
    ("flexoresrot1", "Rotura parcial da origem dos flexores com coleção hemática", "1381", "bullet"),
    ("extensoresrot1", "Lesão de alto grau da origem dos extensores com retração", "1382", "bullet"),

    # ---- bíceps distal / braquial / pronador / tríceps ----
    ("bicepsdist1", "Tendinopatia do bíceps distal com bursite bicipitorradial", "1121", "bullet"),
    ("bicepsdist2", "Leve entesopatia do bíceps na tuberosidade do rádio", "1122", "bullet"),
    ("bicepsdist3", "Leve tendinopatia insercional do bíceps braquial", "1123", "bullet"),
    ("bicepsdist4", "Tendinopatia distal do bíceps com descontinuidades parciais", "693", "bullet"),
    ("bicepsdist5", "Tendinopatia e peritendinite do bíceps distal com fissuras", "1250"),
    ("bicepsdist6", "Edema das fibras da transição miotendínea do bíceps distal", "1321"),
    ("bicepsdist7", "Lacerações da transição miotendínea do bíceps braquial", "1387", "bullet"),
    ("bursabicip1", "Lâmina de líquido na bolsa bicipitorradial", "1318"),
    ("braquial1", "Edema da transição miotendínea do braquial com fissuras", "1253"),
    ("braquial2", "Rotura parcial do ventre muscular do braquial", "1388", "bullet"),
    ("pronador1", "Rotura parcial da cabeça umeral do pronador redondo", "1389", "bullet"),
    ("triceps1", "Mínima entesopatia e peritendinite do tríceps", "1131", "bullet"),
    ("triceps2", "Leve entesopatia do tríceps na inserção distal", "1132", "bullet"),
    ("triceps3", "Incipiente tendinopatia insercional do tríceps", "1133", "bullet"),
    ("triceps4", "Tendinopatia do tríceps com depósito de microcristais", "1136", "bullet"),
    ("triceps5", "Tendinopatia e peritendinite do tríceps com fissuras", "1405"),
    ("triceps6", "Tendinopatia com peritendinite insercional olecraniana do tríceps", "11774"),
    ("bursaolec1", "Distensão da bursa subtendínea do tríceps", "1404"),

    # ---- ligamentos ----
    ("colatrad1", "Estiramento da origem do ligamento colateral radial", "1147", "bullet"),
    ("colatrad2", "Afilamento cicatricial do colateral radial com rotura crônica", "1152"),
    ("colatrad3", "Afilamento dos colaterais reacional à sinovite", "1406"),
    ("colatmed1", "Afilamento cicatricial crônico do complexo ligamentar medial", "1151", "bullet"),
    ("colatmed2", "Rotura parcial do complexo ligamentar colateral medial", "1309"),
    ("colatmed3", "Conclusão — rotura parcial proximal do complexo medial", "1354"),
    ("colatmed4", "Rotura completa do complexo medial com subluxação do nervo ulnar", "1383", "bullet"),
    ("colatuln1", "Alteração cicatricial do ligamento colateral ulnar", "695", "bullet"),
    ("colatuln2", "Estiramento e rotura parcial da banda anterior do colateral ulnar", "1241"),
    ("colatlatuln1", "Rotura parcial do ligamento colateral lateral ulnar", "1304"),
    ("colatlatuln2", "Conclusão — rotura parcial do colateral lateral ulnar", "1349"),
    ("colatlat1", "Rotura de alto grau do complexo ligamentar lateral", "1386", "bullet"),
    ("liganular1", "Estiramento do aspecto posterior do ligamento anular", "1238"),
    ("liganular2", "Estiramento do ligamento anular com edema periligamentar", "1307"),
    ("liganular3", "Conclusão — estiramento do ligamento anular", "1352"),

    # ---- fraturas / trauma ----
    ("fxradio1", "Fratura metaepifisária do rádio proximal sem extensão articular", "1227", "bullet"),
    ("fxradio2", "Fratura metaepifisária do rádio com extensão articular", "1298"),
    ("fxradio3", "Conclusão — fratura do rádio proximal com extensão articular", "1346"),
    ("fxradio4", "Fratura impactada da cabeça do rádio", "1379", "bullet"),
    ("capitulo1", "Impactação cortical do capítulo e do processo coronoide", "1230"),
    ("capitulo2", "Edema contusional do capítulo umeral", "1380", "bullet"),
    ("traumacot1", "Conclusão — alterações pós-traumáticas do cotovelo", "1281"),

    # ---- derrame, partes moles, nervo ----
    ("derramecot1", "Moderado derrame articular no cotovelo com sinovite", "1156"),
    ("derramecot2", "Moderado derrame com espessamento sinovial reacional", "1390", "bullet"),
    ("sinovitecot1", "Sinovite proliferativa do cotovelo com cistos subcorticais", "1401"),
    ("condralcot1", "Afilamento condral difuso do cotovelo com cisto subcondral", "1402"),
    ("erosaocot1", "Erosão da cortical subcondral com invaginação sinovial", "1403"),
    ("edemacot1", "Edema na pele e subcutâneo do cotovelo", "1160"),
    ("edemacot2", "Edema do subcutâneo periarticular posteromedial", "1265"),
    ("edemacot3", "Edema do subcutâneo periarticular posterior", "1330"),
    ("edemacot4", "Edema das partes moles da face posterior do cotovelo", "11775", "bullet"),
    ("edemacot5", "Acentuado edema dos planos mioadiposos do cotovelo", "1391", "bullet"),
    ("linfoepitro1", "Linfonodomegalias na região epitroclear", "1164"),
    ("nervouln1", "Alteração de sinal dos fascículos do nervo ulnar", "1176", "bullet"),
    ("nervouln2", "Espessamento do nervo ulnar no túnel cubital", "1179"),
    ("nervouln3", "Leve espessamento e heterogeneidade do nervo ulnar", "11781", "bullet"),

    # ---- laudos completos ----
    ("rmcotovelo", "RM de cotovelo — normal", "1034-1072"),
    ("rmcotovelo2", "RM de cotovelo — modelo mestre com alterações", "1084-1205 !1108,1145,1155,1159,1163"),
    ("rmcotovelo3", "RM de cotovelo — trauma com fratura do rádio proximal", "1216-1281"),
    ("rmcotovelo4", "RM de cotovelo — trauma com extensão articular", "1287-1363"),
    ("rmcotovelo5", "RM de cotovelo — trauma de alto grau (lista de achados)", "1379-1391"),
    ("rmcotovelo6", "RM de cotovelo — artropatia inflamatória", "1397-1411"),
    ("rmcotovelo7", "RM de cotovelo — tendinopatias e neuropatia ulnar", "11772-11789"),
]
