# Coxa e perna
ENTRADAS = [
    ("#", "COXA / PERNA"),

    # ---- coxa: reto femoral e isquiotibiais ----
    ("retofem2", "Alteração cicatricial do reto femoral proximal e do terço médio", "1438"),
    ("retofem3", "Rotura parcial pregressa cicatrizada do reto femoral", "1464"),
    ("retofem4", "Avulsão das cabeças direta e reflexa do reto femoral", "1560"),
    ("retofem5", "Descontinuidade do tendão central do reto femoral", "1589"),
    ("retofem6", "Lesão completa da transição miotendínea da cabeça indireta", "11640", "bullet"),
    ("retofem7", "Lesão fibrocicatricial da transição miotendínea da cabeça direta", "11641"),
    ("desenluv1", "Desenluvamento do reto femoral com dissociação intermuscular", "1574"),
    ("desenluv2", "Desenluvamento do reto femoral sem retrações significativas", "1582"),
    ("colecaoquadriceps1", "Coleção sero-hemática entre as enteses do quadríceps", "1561"),
    ("bicepsfemoral1", "Rotura completa da junção miotendínea do bíceps femoral", "1437"),
    ("semitendinoso1", "Alteração fibrocicatricial da transição miotendínea do semitendinoso", "1471"),
    ("vastolat1", "Estiramento da junção mioaponeurótica do vasto lateral", "12211", "bullet"),
    ("lipodistrofia1", "Lipodistrofia semicircular — perda focal do tecido adiposo", "1428"),
    ("hemangcoxa1", "Hemangioma intramuscular da coxa", "1526"),
    ("hemangcoxa2", "Características de sinal do hemangioma intramuscular", "1527"),

    # ---- perna: musculatura ----
    ("gastroc1", "Alteração fibrocicatricial musculoaponeurótica do gastrocnêmio medial", "756"),
    ("gastroc2", "Estiramento das fibras distais do gastrocnêmio lateral", "757"),
    ("gastroc3", "Rotura parcial da junção mioaponeurótica do gastrocnêmio medial", "6206"),
    ("gastroc4", "Rotura da junção miofascial do gastrocnêmio medial (British IIa)", "6210"),
    ("gastroc5", "Sequela de rotura da transição miotendínea do gastrocnêmio medial", "6305"),
    ("estiramgastroc1", "Estiramento do gastrocnêmio medial (lesão grau I)", "6234"),
    ("estiramgastroc2", "Rotura parcial do gastrocnêmio medial (lesão grau II)", "6235"),
    ("estiramgastroc3", "Rotura completa do gastrocnêmio medial (lesão grau III)", "6236"),
    ("colecserohem1", "Coleção sero-hemática entre o gastrocnêmio medial e o solear", "6307"),
    ("doms1", "Edema muscular tardio relacionado ao exercício (DOMS)", "6321"),
    ("miosite1", "Padrão de edema muscular — miopatia inflamatória x denervação", "1543"),
    ("hipotrofiaperna1", "Hipotrofia e lipossubstituição difusa da musculatura da perna", "6253"),
    ("fasciatibial1", "Edema da fáscia muscular do tibial anterior", "6240"),

    # ---- perna: osso, estresse e periostite ----
    ("periostite1", "Periostite por estresse do contorno ântero-lateral da tíbia", "6222"),
    ("periostite2", "Periostite por estresse da face póstero-medial da tíbia", "6382"),
    ("periostite3", "Edema da medular da tíbia com periostite por sobrecarga", "6385"),
    ("fxestresse1", "Fratura por estresse da cortical anterior da tíbia", "6232"),
    ("fxestresse2", "Fratura incompleta da cortical medial da tíbia proximal", "6347"),
    ("fxestresse3", "Conclusão — fratura por estresse da tíbia proximal", "6370"),
    ("reacaoestresse1", "Reação por estresse periosteal da diáfise tibial", "6233"),
    ("sobrecargafibula1", "Edema medular da fíbula com periostite por sobrecarga", "6338"),
    ("sobrecargafibula2", "Edema ósseo da diáfise da fíbula por estresse", "6341"),
    ("sobrecargatibia1", "Edema endosteal do terço distal da tíbia por estresse", "6344"),
    ("sobrecargajoelho1", "Focos de edema ósseo nos côndilos femorais por estresse", "6350"),
    ("sobrecargaconc1", "Conclusão — reações ósseas por estresse/sobrecarga", "6367"),
    ("fisetibial1", "Edema perifisário da tíbia distal por sobrecarga", "6398"),
    ("alteracaomedular1", "Alteração de sinal difusa da medular óssea da tíbia", "6256"),
    ("encondromatibia1", "Lesão de matriz condral da tíbia proximal (encondroma)", "1541"),
    ("reconvmed1", "Áreas de medular hematopoiética / reconversão medular", "1542"),

    # ---- perna: nervos, pele e vasos ----
    ("fibularcomum1", "Espessamento do nervo fibular comum com denervação", "6198", "bullet"),
    ("fibularcomum2", "Espessamento do nervo fibular junto à cabeça da fíbula", "6330"),
    ("denervfibular1", "Atrofia com edema do compartimento anterior por denervação (frase interrompida na fonte)", "6326"),
    ("edemasubcut1", "Edema do subcutâneo anterior da perna", "6231"),
    ("edemasubcut2", "Edema difuso da pele e do subcutâneo da perna", "6244"),
    ("afilasubcut1", "Afilamento do tecido adiposo subcutâneo da perna", "6247"),
    ("tvpperna1", "Trombose venosa profunda da veia tibial posterior", "6391"),

    ("grupamentosnl1", "Demais grupamentos musculotendíneos de morfologia e sinal habitual", "6237"),
    ("ventresnl2", "Ventres musculares tróficos", "6356"),
    # ---- laudos completos ----
    ("rmcoxa2", "RM de coxa — atrito iliotibial e sequelas do reto femoral", "1449-1510"),
    ("rmcoxa3", "RM de coxa — hemangioma intramuscular", "1520-1531 !1521"),
    ("rmcoxa4", "RM de coxa — lesão da transição miotendínea do reto femoral", "11635-11652"),
    ("rmcoxa5", "RM de coxa — estiramento do vasto lateral", "12206-12216"),
    ("rmperna2", "RM de pernas e coxas — miosite e reconversão medular", "1536-1546"),
    ("rmperna3", "RM de perna — sequela do gastrocnêmio", "747-764"),
    ("rmperna4", "RM de pernas — normal", "6112-6148"),
    ("rmperna5", "RM de perna — normal com contraste", "6154-6189"),
]
