# Lesões ósseas e tumores, medidas ortopédicas, não-MSK e gerais
ENTRADAS = [
    ("#", "LESÕES ÓSSEAS, TUMORES E OSTEOMIELITE"),

    ("tumorumero1", "Formação expansiva do úmero proximal com componente extraósseo", "776"),
    ("vascularantebraco1", "Lesão vascular/angiodisplásica do antebraço", "7117"),
    ("osteossarcoma1", "Lesão parosteal agressiva da tíbia distal", "9033"),
    ("osteossarcoma2", "Conclusão — lesão parosteal de comportamento agressivo", "9047"),
    ("lesaoagressiva1", "Lesão óssea agressiva da tíbia proximal com reação periosteal", "9057"),
    ("metastasepe1", "Múltiplas lesões ósseas do pé — metástase x sarcoidose", "9115"),
    ("osteomielite1", "Cavidade intraóssea com sequestro e trajeto fistuloso", "9149-9150", "unir"),
    ("osteomielite2", "Focos de sequestro ósseo no interior das coleções", "9164"),
    ("osteomielite3", "Conjunto de achados sugestivo de osteomielite em atividade", "9167"),
    ("osteomielite4", "Conclusão — coleção intraóssea com trajeto fistuloso cutâneo", "9190"),
    ("osteomielite5", "Conclusão — processo infeccioso (osteomielite) em atividade", "9193"),
    ("osteomielite6", "Osteomielite crônica da tíbia com sequestro ósseo", "9210"),
    ("materialosteossint1", "Artefatos metálicos de manipulação cirúrgica no fêmur", "9170"),
    ("bursitetroc1", "Sinais de bursite trocantérica", "9179"),
    ("posoptumor1", "Alteração da medular óssea — lesão x manipulação cirúrgica", "11011"),
    ("ressectumor1", "Controle de ressecção parcial do membro superior", "11019"),
    ("infartomedular1", "Alteração da medular óssea umeral — provável infarto medular", "11025"),
    ("posoptumor2", "Conclusão — controle pós-operatório de ressecção", "11038"),
    ("lipossarcoma1", "Formação expansiva adiposa do braço — lipoma x lipossarcoma", "11055"),
    ("tcgdedo1", "Lesão nodular do dedo — tumor de células gigantes da bainha tendínea", "11061"),
    ("linfoma1", "Formação expansiva pré-vertebral com extensão foraminal (linfoma?)", "11071"),

    ("ressectumor2", "Alteração fibrocicatricial da tela subcutânea pós-cirúrgica", "11021"),
    ("ressectumor3", "Alterações fibrocicatriciais com lipossubstituição muscular", "11023"),
    ("sequelacondilos1", "Alteração morfoestrutural sequelar dos côndilos femorais", "9173"),
    
    ("miotendinnl3", "Demais planos musculares, tendíneos e aponeuróticos sem anormalidades", "9038"),
    
    ("feixevascnl1", "Feixe vásculo-neural livre", "9182"),
    
    ("corticalnl1", "Sem sinais de rotura da cortical ou componente extraósseo", "11014"),
    ("comparacao5", "Comparação — análise comparativa, com a data a preencher", "11017"),
    ("metodosefse1", "Técnica — SE e FSE multiplanares de 4 mm com contraste", "9139"),
    
    ("#", "MEDIDAS E ÂNGULOS ORTOPÉDICOS"),

    ("tcquadril6", "TC de coxa e quadril — versão acetabular e femoral, ângulo alfa", "10815-10830"),
    ("tcquadril7", "TC de coxa e quadril — medidas com alterações degenerativas", "10849-10867"),
    ("tcperfiltors", "TC — perfil torsional do fêmur e da tíbia", "10879-10902"),
    ("retroversaofem1", "Ângulo de versão femoral — retroversão", "4028", "bullet"),
    ("retroversaofem2", "Conclusão — retroversão femoral", "4037", "bullet"),
    ("tcquadril8", "TC de quadril — cálculo de versão femoral", "12572-12587"),

    ("#", "NÃO-MSK"),

    ("aneurismaaorta1", "Aneurisma fusiforme da aorta abdominal com trombo mural", "89", "bullet"),
    ("aneurismaaorta3", "Aorta com dilatação aneurismática infrarrenal (medidas)", "113-115", "unir"),
    ("usaorta", "US Doppler de aorta abdominal e ilíacas — aneurisma", "89-103"),
    ("trombosejugular1", "Trombose crônica da veia jugular interna com colaterais", "457"),
    ("trombosejugular2", "Conclusão — trombose venosa crônica da jugular interna", "463", "bullet"),
    ("usdopplercerv", "US Doppler venoso cervical — trombose da jugular interna", "456-463"),
    ("figado1", "Fígado com contornos serrilhados e alteração ecotextural difusa", "782"),
    ("dopplerporta1", "Doppler portal — veia porta, supra-hepáticas e esplênica", "785-787", "flat"),
    ("vesicula1", "Vesícula biliar com paredes espessadas secundário a ascite", "789"),
    ("baco1", "Esplenomegalia", "792"),
    ("ascite1", "Ascite de grande volume", "804"),
    ("hipertensaoportal1", "Opinião — hepatopatia crônica com hipertensão portal", "807-812"),
    ("usabdome", "US de abdome total — hepatopatia crônica com hipertensão portal", "779-812 !802"),
    ("esteatoseus1", "Fígado com ecogenicidade difusamente aumentada", "11322"),
    ("esteatoseus2", "Aumento difuso da ecogenicidade hepática (esteatose)", "11323"),
    ("fistulaperianal1", "Máscara — fístula perianal com classificação e trajeto", "11426", "bullet"),
    ("rmpelvefistula", "RM da pelve — pesquisa de fístulas perianais", "11417-11450"),
    ("opacidadestorax1", "Opacidades consolidativas com vidro fosco e espessamento septal", "11373"),
    ("pbmicose1", "Opacidades em vidro fosco — DPOC e/ou paracoccidioidomicose", "11407"),
    ("tctorax2", "TC de tórax — coleção da parede torácica e opacidades", "12466-12489"),
    ("tccorpototal", "TC de corpo total — pesquisa de mieloma múltiplo", "9220-9238"),
    ("tirads1", "TI-RADS — conduta por categoria", "10995-11000", "flat"),

    ("#", "GERAIS / OBSERVAÇÕES"),

    ("edemainsercional1", "Edemas subcorticais em inserções ligamentares e tendíneas — artropatia inflamatória", "11331"),
    ("obstumorresid1", "Ressalva — sugerir RM com contraste para lesão tumoral residual cervical", "9591"),
    ("demaisestrut1", "Demais estruturas com morfologia preservada", "4353"),
    ("demaisnl1", "Demais estruturas sem particularidades", "4280"),
    ("examedirigpe1", "Abertura — exame direcionado para estudo do mediopé", "5874"),
    ("semabscesso1", "Não se caracterizam coleções ou abscessos", "6283"),
    ("pormenorizado1", "Demais aspectos pormenorizados no corpo do laudo", "6448"),
    ("artefatos1", "Exame prejudicado por artefatos de movimentação", "1028"),
    ("equipamentoaberto1", "Exame realizado em equipamento aberto de baixo campo", "734"),
    ("adendo1", "Adendo de laudo — alteração da medular óssea", "744"),
    ("tomonota1", "Sem traços de fratura desalinhados — sugerir RM se persistir suspeita", "962"),
    ("obstccoluna1", "Obs. — sugerir RM para partes moles e discos", "9245"),
    ("obstcpartesmoles1", "Ressalva — limitação da TC para partes moles", "9249"),
    ("comparacao1", "Comparação — sem mudanças evolutivas significativas", "2316"),
    ("comparacao2", "Comparação — estudos anteriores não disponíveis", "323"),
    ("comparacao3", "Comparação — em relação ao exame anterior, sem alterações", "4006"),
    ("comparacao4", "Comparação — estudos anteriores não disponíveis para análise", "4007"),
    ("obsjoelhoroto1", "Obs. — surgimento de tecido cicatricial no LCA roto", "10989"),
    ("protocolotorax1", "Protocolo — marcação e sequências para estudo dirigido do tórax", "2691"),
]
