# Joelho
ENTRADAS = [
    ("#", "JOELHO"),

    # ---- meniscos ----
    ("meniscnl1", "Meniscos com morfologia e sinal normais", "2874"),
    ("meniscmed1", "Alteração degenerativa intrassubstancial do menisco medial", "2875"),
    ("meniscmed2", "Alteração degenerativa com irregularidade da margem livre", "2878"),
    ("meniscmed3", "Alteração degenerativa com redução volumétrica e extrusão", "2879"),
    ("meniscmed4", "Rotura horizontal do corno posterior do menisco medial", "2880"),
    ("meniscmed5", "Rotura em alça de balde do menisco medial", "2881"),
    ("meniscmed6", "Rotura radial da margem livre do corno posterior", "2882"),
    ("meniscmed7", "Rotura radial na transição corpo/corno posterior", "2883"),
    ("meniscmed8", "Rotura de alto grau da raiz posterior do menisco medial", "2884"),
    ("meniscmed9", "Rotura complexa do corno anterior e corpo do menisco medial", "2886"),
    ("meniscmed10", "Redução volumétrica com fissura periférica do corno posterior", "2887"),
    ("meniscmed11", "Rotura horizontal com fragmento no recesso menisco-tibial", "2890"),
    ("meniscmed12", "Fina rotura do corpo com fragmento meniscal deslocado", "2894"),
    ("meniscmed13", "Redução volumétrica por meniscectomia parcial", "3477"),
    ("meniscmed14", "Degeneração difusa do menisco medial com aspecto fragmentado", "3546"),
    ("menisclat1", "Rotura complexa do corno anterior e corpo do menisco lateral", "2885"),
    ("menisclat2", "Redução volumétrica pós-cirúrgica do menisco lateral", "2888"),
    ("menisclat3", "Alteração degenerativa do corno anterior do menisco lateral", "2889"),
    ("menisclat4", "Rotura longitudinal vertical periférica do menisco lateral", "3375"),
    ("menisclat5", "Alteração pós-contusional do corno anterior do menisco lateral", "3376"),
    ("menisclat6", "Alteração degenerativa do corno anterior com fragmentação", "3549"),
    ("meniscocaps1", "Estiramento da junção meniscocapsular do menisco medial", "3298"),
    ("meniscocaps2", "Estiramento da junção meniscocapsular do menisco lateral", "3305"),
    ("meniscocaps3", "Irregularidade meniscocapsular com extrusão do corpo", "3369"),
    ("meniscocaps4", "Edema da junção meniscocapsular com degeneração meniscal", "3370"),
    ("meniscocaps5", "Irregularidade meniscocapsular do menisco lateral", "3377"),
    ("raizmenisc1", "Entesopatia da fixação tibial da raiz posterior do menisco medial", "2870"),
    ("raizmenisc2", "Desinserção da raiz anterior do menisco lateral", "2916"),
    ("conflitoosteo1", "Conflito osteomeniscal — irregularidade do rebordo tibial", "2891"),

    # ---- ligamentos cruzados ----
    ("cruzadosnl1", "Ligamentos cruzados e colaterais íntegros", "2863"),
    ("lcaroto1", "Leve afilamento da porção proximal do ligamento cruzado anterior", "2832"),
    ("lcaroto2", "Alteração degenerativa do ligamento cruzado anterior", "2835"),
    ("lcaroto3", "Rotura parcial do ligamento cruzado anterior", "2836"),
    ("lcaroto4", "Rotura completa proximal do ligamento cruzado anterior", "2841"),
    ("lcaroto5", "Afilamento proximal do LCA por rotura parcial pregressa", "2844"),
    ("lcaroto6", "Afilamento das fibras do LCA — degeneração x sequela", "2847"),
    ("lcaroto7", "Rotura completa crônica do ligamento cruzado anterior", "2854"),
    ("lcaroto8", "Rotura completa do LCA na origem com fibras horizontalizadas", "3314"),
    ("lcaroto9", "Rotura completa no terço médio do LCA", "3315"),
    ("lcaroto10", "Rotura parcial do LCA com edema periligamentar", "3316"),
    ("lcpost1", "Rotura parcial de alto grau do ligamento cruzado posterior", "2850"),
    ("lcpost2", "Rotura parcial extensa do ligamento cruzado posterior", "2853"),
    ("lcpost3", "Alteração degenerativa/cicatricial do cruzado posterior", "2855"),
    ("lcpnl1", "Ligamento cruzado posterior íntegro", "3333"),
    ("lcpnl2", "Ligamento cruzado posterior verticalizado, porém íntegro", "3334"),

    # ---- ligamentos colaterais e canto póstero-lateral ----
    ("colatmedjoe1", "Rotura parcial do ligamento colateral medial", "2856"),
    ("colatmedjoe2", "Espessamento fibrocicatricial do colateral medial", "2857"),
    ("colatmedjoe3", "Espessamento crônico do colateral medial proximal", "2861"),
    ("colatmedjoe4", "Estiramento das porções superficial e profunda do colateral medial", "3282"),
    ("colatmedjoe5", "Rotura parcial do colateral medial com edema periligamentar", "3330"),
    ("colatlatjoe1", "Estiramento do ligamento colateral lateral distal", "2860"),
    ("colatlatjoe2", "Estiramento do ligamento colateral lateral", "3327"),
    ("colatlatjoe3", "Alterações pós-estiramento do ligamento colateral lateral", "3329"),
    ("colatlatjoe4", "Espessamento cicatricial do ligamento colateral lateral", "3534"),
    ("colatjoe1", "Espessamento e alteração de sinal dos ligamentos colaterais", "3209"),
    ("colatjoe2", "Edema periligamentar aos colaterais indicando estiramento", "3326"),
    ("cantopostlat1", "Estiramento das estruturas do canto póstero-lateral", "2862"),
    ("cantopostlat2", "Rotura do colateral lateral e do canto póstero-lateral", "3319"),
    ("popliteofib1", "Estiramento dos ligamentos poplíteo-arqueado e popliteofibular", "3337"),
    ("capsulapost1", "Estiramento da cápsula articular posterior", "3340"),
    ("anterolateral1", "Lesão do ligamento anterolateral", "3288"),
    ("bandailio1", "Síndrome da banda iliotibial — atrito no côndilo lateral", "2864"),
    ("bandailio2", "Entesopatia do trato iliotibial na inserção tibial", "2865"),

    # ---- cartilagem e osso ----
    ("condropat1", "Condropatia patelar com fissuras condrais", "2811"),
    ("condropat2", "Condropatia patelar com fissuras profundas em ambas as facetas", "3380"),
    ("trocleanl1", "Cartilagem da tróclea femoral preservada", "2816"),
    ("condrotro1", "Condropatia da tróclea femoral", "2817"),
    ("condrofemtib1", "Afilamento condral nas áreas de carga femorotibiais", "2904"),
    ("condrofemtib2", "Afilamento condral lateral com edema ósseo periférico", "2912"),
    ("artrofemtib1", "Artropatia degenerativa femorotibial bicompartimental", "2908"),
    ("artrofemtib2", "Artropatia bicompartimental com erosões profundas laterais", "2909"),
    ("artrofemtib3", "Artropatia medial acentuada com fraturas subcondrais impactadas", "2910"),
    ("artrofemtib4", "Artropatia acentuada com geodo no platô tibial lateral", "2919"),
    ("artrofemtib5", "Artropatia bicompartimental com exposição óssea", "3540"),
    ("artrofempat1", "Artropatia degenerativa femoropatelar", "3561"),
    ("edemamecanico1", "Edema ósseo periférico do compartimento medial", "2915"),
    ("cistoespinhas1", "Alterações císticas nas eminências intercondilianas", "2871"),
    ("espinhastibiais1", "Fragmentação sequelar das espinhas tibiais", "3543"),
    ("fxsubcondtibial1", "Fratura subcondral periférica do platô tibial medial", "2897"),
    ("fxsubcondtibial2", "Fratura subcondral do terço posterior do platô lateral", "3355"),
    ("fxplatotibial1", "Fratura do platô tibial cominutiva (Schatzker VI)", "3008"),
    ("fxplatotibial2", "Fraturas impactadas dos planaltos tibiais e côndilo lateral", "3352"),
    ("impactacaotibial1", "Impactação das corticais dos rebordos posteriores dos platôs", "3349"),
    ("impactacaocondilo1", "Impactação anterolateral do côndilo femoral lateral", "3357"),
    ("contusaocondilo1", "Contusão óssea do côndilo femoral lateral", "3293"),
    ("contusaocondilo2", "Edema pós-contusional do côndilo femoral medial", "3356"),
    ("contusaojoelho1", "Edema pós-contusional dos côndilos e platôs tibiais", "3358"),
    ("fxfibula1", "Fratura da cabeça da fíbula com edema medular", "3361"),
    ("osteocondrjoe1", "Osteocondrite dissecante do côndilo femoral medial", "3135", "bullet"),
    ("fragmentocondral1", "Fragmento condral no recesso anterior infrapatelar", "3699"),
    ("destaccondral1", "Destacamento condral do côndilo femoral lateral", "3700"),
    ("ossificacaocart1", "Ossificação da cartilagem habitual para a faixa etária", "3259"),
    ("mosaicoplastia1", "Alteração óssea e subcondral por mosaicoplastia", "2740"),
    ("corpoarticular1", "Corpo intra-articular não ossificado x proliferação sinovial", "2796"),

    # ---- patela e mecanismo extensor ----
    ("patelaalta1", "Patela alta, basculada e lateralizada", "2820"),
    ("patelaalta2", "Patela alta pelo índice de Caton-Deschamps", "2821"),
    ("patelaalta3", "Patela alta com índice de Insall-Salvati e tróclea rasa", "2823"),
    ("trocleadisp1", "Tróclea rasa por hipoplasia da faceta medial", "2822"),
    ("trocleadisp2", "Patela alta com sulco troclear displásico", "3671"),
    ("patelabip1", "Patela bipartida com microinstabilidade", "2824"),
    ("defeitodorsal1", "Defeito dorsal da patela (variante anatômica)", "3002"),
    ("luxpatela1", "Patela alta, subluxada e inclinada lateralmente", "3655"),
    ("luxpatela2", "Edema ósseo com impacção por luxação patelar", "3657"),
    ("luxpatela3", "Conclusão — episódio recente de luxação lateral da patela", "3661"),
    ("luxpatela4", "Luxação lateral transitória recente da patela", "3674"),
    ("luxpatela5", "Luxação lateral transitória com afilamento do retináculo medial", "3696"),
    ("lpfm1", "Rotura extensa do ligamento patelofemoral medial e do retináculo", "3656"),
    ("lpfm2", "Rotura do retináculo medial com extensão aos patelofemoral e patelotibial", "3681"),
    ("quadriceps1", "Leve tendinopatia insercional do quadríceps", "2935"),
    ("quadriceps2", "Tendinopatia insercional do quadríceps com espessamento", "2936"),
    ("quadriceps3", "Incipiente entesopatia do quadríceps", "2937"),
    ("quadriceps4", "Entesopatia distal do quadríceps com entesófito", "2938"),
    ("quadriceps5", "Tendão do quadríceps afilado e irregular", "3207"),
    ("quadriceps6", "Rotura parcial extensa e transfixante do tendão do quadríceps", "615"),
    ("tendpatelar1", "Entesopatia do patelar na tuberosidade anterior da tíbia", "2941"),
    ("tendpatelar2", "Tendinopatia do patelar com rotura parcial justainsercional", "2942"),
    ("tendpatelar3", "Espessamento e alteração de sinal do ligamento patelar", "3208"),
    ("tendpatelar4", "Espessamento cicatricial do ligamento patelar", "3558"),
    ("entesofitopat1", "Entesófitos quadricipitais e patelares proximais", "2931"),
    ("avulsaopatelar1", "Fratura avulsiva da inserção distal do tendão patelar", "3237", "bullet"),
    ("apofisitepat1", "Apofisite do polo inferior da patela", "3241", "bullet"),
    ("osgood1", "Sequela de Osgood-Schlatter — osteo-hipertrofia da tuberosidade", "3040"),
    ("osgood2", "Sequela de Osgood-Schlatter com ossificação e edema", "3043"),
    ("osgood3", "Diminuta ossificação — sequela de Osgood-Schlatter", "3045"),
    ("osgood4", "Sequela de Osgood-Schlatter com tendinopatia do patelar", "3048"),
    ("osgood5", "Sequela de Osgood-Schlatter com bursite infrapatelar profunda", "3051"),
    ("osgood6", "Osgood-Schlatter em criança — fragmentação da apófise", "3057"),
    ("osgood7", "Osgood-Schlatter com fissura das fibras distais do patelar", "3141"),
    ("sinding1", "Sequela de Sinding-Larsen-Johansson", "3065", "bullet"),
    ("sinding2", "Proeminência óssea do polo inferior da patela", "3066", "bullet"),
    ("sinding3", "Hipertrofia e fragmentação do polo inferior da patela", "3136", "bullet"),
    ("hoffa1", "Edema da gordura infrapatelar — hiperpressão do mecanismo extensor", "2954"),
    ("hoffa2", "Alterações fibrocicatriciais da gordura de Hoffa", "3497"),
    ("hoffa3", "Estrias cicatriciais na gordura de Hoffa", "3552"),
    ("hoffa4", "Traves cicatriciais de Hoffa com tendinopatia do patelar", "3624"),
    ("bursaprepat1", "Bursite pré-patelar", "2949"),

    # ---- derrame, cistos e fossa poplítea ----
    ("derramejoe1", "Pequeno derrame articular com sinovite reacional", "2958"),
    ("derramejoe2", "Derrame com corpos condrais no recesso posterior", "2959"),
    ("lipohemartrose1", "Derrame articular com lipo-hemartrose", "3346"),
    ("baker1", "Cisto poplíteo (Baker) com septações e rotura parcial", "2980"),
    ("baker2", "Cisto de Baker roto com extravasamento líquido", "2981"),
    ("baker3", "Volumoso cisto de Baker com contornos lobulados", "2982"),
    ("baker4", "Diminuto cisto poplíteo", "3505"),
    ("baker5", "Pequeno cisto poplíteo medial alongado", "3564"),
    ("bolsagastroc1", "Lâmina líquida na bolsa do gastrocnêmio medial/semimembranoso", "2979"),
    ("cistoroto4", "Rotura de cisto artrossinovial com edema pericapsular", "2976"),
    ("cistoganglionar1", "Cisto gangliônico junto à inserção tibial do LCA", "3244", "bullet"),
    ("poplite1", "Distensão da bainha do poplíteo com corpos livres", "2973"),
    ("gastrocjoe1", "Tendinopatia da origem do gastrocnêmio medial com cistos", "2962"),
    ("gastrocjoe2", "Tendinopatia do gastrocnêmio medial com rotura parcial insercional", "2965"),
    ("pataanserina1", "Peritendinite distal da pata anserina", "3392"),
    ("pataanserina2", "Peritendinite distal da pata anserina sem roturas", "3567"),
    ("edemajoelho1", "Edema difuso dos planos periarticulares do joelho", "3210"),
    ("edemajoelho2", "Edema difuso da tela subcutânea do joelho", "3389"),
    ("fibularcomum3", "Leve espessamento do nervo fibular comum", "3211"),

    # ---- pós-operatório: reconstrução do LCA e prótese ----
    ("lcarecon1", "Abordagem cirúrgica para reconstrução do LCA com materiais de síntese", "3442"),
    ("lcarecon2", "Reconstrução do LCA com neoligamento íntegro", "3443"),
    ("lcarecon3", "Reconstrução do LCA com rerrotura completa do enxerto", "3444"),
    ("lcarecon4", "Neoligamento íntegro com tecido fibrocicatricial adjacente", "3445"),
    ("lcarecon5", "Neoligamento íntegro com sinal discretamente heterogêneo", "3454"),
    ("lcarecon6", "Neoligamento não identificado, sugerindo lesão completa", "3455"),
    ("lcarecon7", "Degeneração do neoligamento com rotura parcial das fibras", "3458"),
    ("lcarecon8", "Conclusão — controle pós-reconstrução do LCA", "3517"),
    ("lcarecon9", "Manipulação cirúrgica com túneis ósseos de aspecto habitual", "3525"),
    ("lcarecon10", "Rotura completa do neoligamento cruzado anterior", "3528"),
    ("lcarecon11", "Conclusão — reconstrução pregressa com rotura do neoligamento", "3590"),
    ("lcarecon12", "Reconstrução do LCA com túneis em posicionamento habitual", "143"),
    ("lcarecon13", "Alterações fibrocicatriciais na gordura de Hoffa e pata anserina", "144"),
    ("lcarecon14", "Controle pós-operatório recente de reconstrução do LCA", "145"),
    ("tuneltibial1", "Edema e cistos junto ao trajeto do túnel tibial", "3448"),
    ("tuneltibial2", "Alargamento do túnel tibial com conteúdo sinovial", "3451"),
    ("artrofibrose1", "Tecido cicatricial junto ao neoligamento sem artrofibrose", "3461"),
    ("artrofibrose2", "Foco de artrofibrose / lesão ciclope", "3464"),
    ("artrofibrose3", "Artrofibrose anterior extensa", "3465"),
    ("artrofibrose4", "Tecido fibrocicatricial compatível com artrofibrose", "3466"),
    ("sitiodoador1", "Bifidez do tendão patelar — sítio doador de enxerto", "3484"),
    ("sitiodoador2", "Manipulação cirúrgica do tendão patelar com sinais de integração", "3485"),
    ("sitiodoador3", "Falha central do tendão patelar — sítio doador", "3486"),
    ("sitiodoador4", "Afilamento do grácil e semitendinoso — sítio doador", "3489"),
    ("protesejoelho1", "Lise óssea junto ao componente tibial da prótese", "3618"),
    ("protesejoelho2", "Lise na interface óssea dos componentes femoral e patelar", "3619"),
    ("protjoelhoinf1", "Retirada de material protético com cimento ósseo residual", "3201"),
    ("protjoelhoinf2", "Cavidades medulares ocupadas por tecido de granulação", "3202"),
    ("protjoelhoinf3", "Irregularidade da superfície articular patelar", "3203"),
    ("protjoelhoinf4", "Derrame com espessamento e realce sinovial", "3204"),
    ("protjoelhoinf5", "Achados inespecíficos — pioartrite e osteomielite", "3205"),
    ("protjoelhoinf6", "Artefatos e calcificações intra e periarticulares", "3206"),
    ("osteotomia1", "Pós-operatório de osteotomia valgizante da tíbia", "3020"),
    ("materialfemur1", "Material metálico no fêmur distal com artefatos", "3032"),

    # ---- lesões ósseas e depósito ----
    ("estressejoelho1", "Reação por estresse metadiafisária femoral", "3024"),
    ("fxestressetibia1", "Fratura por estresse póstero-medial da tíbia proximal", "3191"),
    ("fxestressetibia2", "Alterações inflamatórias reacionais à fratura de estresse", "3194"),
    ("fxestressetibia3", "Fratura incompleta da tíbia proximal por estresse", "3197"),
    ("desmoide1", "Defeito fibroso cortical / desmoide cortical do fêmur distal", "3073", "bullet"),
    ("desmoide2", "Desmoide cortical na origem do gastrocnêmio medial", "3074", "bullet"),
    ("desmoide3", "Desmoide cortical relacionado à tração mecânica", "3075", "bullet"),
    ("fibromanaoos1", "Fibroma não ossificante da tíbia proximal", "3077", "bullet"),
    ("fibromanaoos2", "Fibroma não ossificante da diáfise distal do fêmur", "3081", "bullet"),
    ("fibromanaoos3", "Sequela de fibroma não ossificante da metáfise tibial", "3084", "bullet"),
    ("fibromanaoos4", "Fibroma não ossificante da tíbia distal com realce", "3092", "bullet"),
    ("fxpatologicatibia1", "Fratura patológica junto a fibroma não ossificante", "3093"),
    ("encondromafemur1", "Lesão de provável natureza condral do fêmur (encondroma)", "3108"),
    ("osteocondrtib1", "Osteocondroma da metáfise proximal da tíbia", "3185"),
    ("infartoosseo1", "Infarto ósseo da região diafisária distal do fêmur", "3126"),
    ("infartoosseo2", "Infartos ósseos múltiplos do fêmur e da tíbia", "3129"),
    ("lipoma1", "Lipoma do subcutâneo adjacente ao maléolo lateral", "3174", "bullet"),
    ("lipoma2", "Lipoma intraósseo da tíbia proximal", "3175", "bullet"),
    ("hemangjoelho1", "Lesão vascular no recesso súpero-medial do joelho", "3155"),
    ("hemangjoelho2", "Lesão vascular no terço distal da coxa", "3157"),
    ("hemangjoelho3", "Lesão vascular entre o gastrocnêmio medial e o semimembranoso", "3249"),
    ("gotajoelho1", "Depósito de microcristais no tendão patelar (gota)", "3114"),
    ("gotajoelho2", "Depósito de cristais envolvendo o tendão poplíteo", "3115"),
    ("gotajoelho3", "Tendinopatia do poplíteo com erosões por microcristais", "3122"),
    ("reconvmed2", "Heterogeneidade da medula óssea por reconversão", "3010"),
    ("reconvmed3", "Reconversão medular — correlação com doença hematológica", "3014"),

    ("sinovitevilo1", "Conclusão — sinovite vilonodular difusa a considerar", "248", "bullet"),
    ("patelastc1", "TC — patelas lateralizadas em extensão e centradas na flexão", "3777-3779", "flat"),
    ("luxpatela6", "Impacção óssea por luxação patelar lateral recente", "12083"),
    ("flapcondral1", "Imagem alongada no contorno da faceta medial (flap condral?)", "12086"),
    ("erosaopatelar1", "Erosão condral do vértice patelar", "12085"),
    ("fragmentocondral2", "Fragmento osteocondral deslocado para o intercôndilo", "12087"),
    ("feixesjoelhonl1", "Demais feixes neurovasculares sem particularidades", "3212"),
    ("patelaalta4", "Patela alta com báscula lateral", "12081"),
    ("trocleadisp3", "Tróclea rasa", "12082"),
    ("derramejoe3", "Moderado derrame articular e sinovite", "12084"),
    # ---- laudos completos ----
    ("rmjoelho2", "RM de joelho — modelo mestre com alternativas", "2747-2781"),
    ("rmjoelho3", "RM de joelho — modelo mestre com todas as variantes", "2801-2992"),
    ("rmjoelho4", "RM de joelho — rotura aguda do LCA", "3272-3421"),
    ("rmjoelho5", "RM de joelho — controle de reconstrução do LCA", "3429-3517"),
    ("rmjoelho6", "RM de joelho — rotura do neoligamento com artrose", "3522-3608 !3578"),
    ("rmjoelho7", "RM de joelho — soltura de prótese total", "3614-3626"),
    ("rmjoelho8", "RM de joelho — modelo mestre com alternativas (Relatório/I.D.)", "4049-4068"),
    ("rmjoelho9", "RM de joelho — artrose (modelo Relatório/I.D.)", "4072-4098"),
    ("rmjoelho10", "RM de joelho — rotura do LCA (modelo Relatório/I.D.)", "4102-4130"),
    ("rmjoelho11", "RM de joelho — reconstrução do LCA (modelo Relatório/I.D.)", "4137-4158"),
    ("rmjoelho12", "RM de joelho — luxação patelar (modelo Relatório/I.D.)", "4168-4192"),
    ("rmjoelho13", "RM de joelho — artrose com rotura complexa do menisco lateral", "306-331"),
    ("rmjoelho14", "RM de joelho — roturas horizontais e cisto de Baker roto", "342-366"),
    ("rmjoelho15", "RM de joelho — condropatia patelotroclear", "522-542"),
    ("rmjoelho16", "RM de joelho — condropatia com hiperpressão do extensor", "588-609"),
    ("rmjoelho17", "RM de joelho — infartos ósseos", "633-644"),
    ("rmjoelho18", "RM de joelho — lesão óssea agressiva da tíbia proximal", "9070-9099"),
    ("rmjoelho19", "RM de joelho — acondroplasia com menisco discoide", "11516-11540"),
    ("rmjoelho20", "RM de joelho — acondroplasia com lesão do menisco discoide", "11541-11567"),
    ("rmjoelho21", "RM de joelho — controle evolutivo pós-meniscectomia", "11658-11692"),
    ("rmjoelho22", "RM de joelho — artrose tricompartimental", "12009-12033"),
    ("rmjoelho23", "RM de joelho — rotura do LCA e das raízes meniscais", "12037-12062"),
    ("tcjoelho", "TC de joelho — medidas de alinhamento patelar", "3724-3745"),
    ("tcjoelhos", "TC dos joelhos — TA-GT e medidas bilaterais", "3749-3772"),
    ("tcjoelho2", "TC dinâmica dos joelhos — modelo com medidas", "3813-3836"),
    ("tcjoelho9", "TC dinâmica dos joelhos — tabela de tilt e subluxação patelar (células do export)", "3843-3864", "flat"),
    ("tcjoelho3", "TC dinâmica dos joelhos — extensão e flexão de 10º e 30º", "3880-3904"),
    ("tcjoelho4", "TC dinâmica dos joelhos — TA-GT, inclinação e altura patelar", "3908-3948"),
    ("tcjoelho5", "TC dos joelhos — modelo com valores de referência", "3957-4012"),
    ("tcjoelho6", "TC de joelho — medidas ortopédicas, normal", "9868-9889"),
    ("tcjoelho7", "TC dos joelhos — artropatia degenerativa", "9893-9910"),
    ("tcjoelho8", "TC de joelho — luxação patelar com TA-GT", "9914-9967"),
]
