# Ombro — (trigger, label, linhas na fonte, [modo])
ENTRADAS = [
    ("#", "OMBRO"),

    # ---- manguito rotador: supraespinhal / infraespinhal ----
    ("supra1", "Tendinopatia do supra e infraespinhal com rotura focal insercional", "4637"),
    ("supra2", "Tendinopatia moderada do supra e infraespinhal com roturas justainsercionais", "4639"),
    ("supra3", "Tendinopatia do supra e infraespinhal com rotura transfixante", "4642"),
    ("supra4", "Tendinopatia do supraespinhal e fibras superiores do infraespinhal", "4769"),
    ("supra5", "Rotura parcial intrassubstancial do supraespinhal (< 50%)", "4772"),
    ("supra6", "Rotura parcial insercional articular do supraespinhal (> 50%)", "4773"),
    ("supra7", "Rotura parcial do contorno bursal/articular do terço médio do supraespinhal", "4774"),
    ("supra8", "Rotura extensa insercional das fibras anteriores e médias do supraespinhal", "4782"),
    ("supra9", "Pequena rotura parcial das fibras articulares anteriores do supraespinhal", "4785"),
    ("supra10", "Rotura transfixante completa do supra e infraespinhal com cisto satélite", "4790"),
    ("supra11", "Rotura transfixante do supraespinhal no terço médio e anterior", "4791"),
    ("supra12", "Rotura transfixante das fibras anteriores do supraespinhal", "4794"),
    ("supra13", "Rotura transfixante completa do supra e infraespinhal com retração de 3,6 cm", "4955"),
    ("supra14", "Tendinopatia leve do supraespinhal com fissuras insercionais", "5218"),
    ("supra15", "Rotura completa transfixante do supra e infraespinhal (Goutallier III/IV)", "5303"),
    ("infra1", "Tendinopatia do infraespinhal com cisto satélite na transição miotendínea", "4641"),
    ("infra2", "Rotura transfixante do infraespinhal com delaminação das fibras", "4777"),
    ("infra3", "Tendinopatia do infraespinhal sem roturas", "5351"),
    ("infracalc1", "Tendinopatia calcária do infraespinhal com diminutos focos", "4638"),
    ("infracalc2", "Tendinopatia calcária do infraespinhal junto às fibras inferiores", "4803"),
    ("supracalc1", "Tendinopatia calcária do supraespinhal com bursite reacional", "4804"),
    ("supracalc2", "Tendinopatia calcária do supra e infraespinhal", "4805"),

    # ---- subescapular ----
    ("subesc1", "Tendinopatia do subescapular com fissuras intrassubstanciais", "4810"),
    ("subesc2", "Tendinopatia do subescapular com rotura parcial insercional superior", "4811"),
    ("subesc3", "Rotura transfixante das fibras superiores e médias do subescapular", "4961"),
    ("subesc4", "Tendinopatia do subescapular com pequena rotura parcial insercional", "4962"),
    ("subesc5", "Tendinopatia do subescapular sem roturas", "5078"),
    ("subesc6", "Tendinopatia leve do subescapular com fissura insercional", "5221"),
    ("subesc7", "Leve tendinopatia do subescapular sem roturas", "5354"),

    # ---- cabo longo do bíceps ----
    ("cablongo1", "Tendinopatia do cabo longo do bíceps com rotura longitudinal", "4640"),
    ("cablongo2", "Tendinopatia do cabo longo do bíceps com distensão da bainha", "4816"),
    ("cablongo3", "Tendinopatia do cabo longo do bíceps com subluxação medial", "4817"),
    ("cablongo4", "Tenotomia com tenodese do cabo longo do bíceps", "4821"),
    ("cablongo5", "Rotura completa do cabo longo do bíceps com retração do coto", "4824"),
    ("cablongo6", "Cabo longo do bíceps subluxado pela rotura do subescapular", "4966"),
    ("cablongo7", "Tenossinovite do cabo longo do bíceps com delaminações extra-articulares", "4967"),
    ("cablongo8", "Tendinopatia do cabo longo do bíceps no trajeto intra-articular", "5224"),
    ("cablongo9", "Leve tendinopatia do cabo longo do bíceps sem roturas", "5259"),
    ("cablongo10", "Leve tendinopatia intra-articular do cabo longo do bíceps", "5357"),
    ("cablongo11", "Indefinição do cabo longo do bíceps por tenotomia", "5360"),

    # ---- acromioclavicular / acrômio ----
    ("acnormal1", "Relação acromioclavicular preservada", "4658"),
    ("acnormal2", "Relação acromioclavicular preservada / com espessamento capsuloligamentar", "4743"),
    ("artroac1", "Artrose acromioclavicular com edema subcondral", "4661"),
    ("artroac2", "Reação osteo-hipertrófica da clavícula distal", "4744"),
    ("artroac3", "Hipertrofia capsuloligamentar acromioclavicular de natureza mecânica", "4745"),
    ("artroac4", "Artropatia degenerativa acromioclavicular com derrame", "4746"),
    ("artroac5", "Artropatia degenerativa acromioclavicular com alteração cicatricial", "4907"),
    ("artroac6", "Relação acromioclavicular preservada com diástase articular", "4898"),
    ("artroac7", "Artropatia acromioclavicular com esporão subacromial", "4935", "bullet"),
    ("artroac8", "Artropatia degenerativa acromioclavicular com esclerose subcondral", "4938", "bullet"),
    ("artroac9", "Artrose acromioclavicular com esporão ósseo subacromial", "4941"),
    ("artroac10", "Artropatia degenerativa acromioclavicular com cistos subcondrais", "5212"),
    ("artroac11", "Discreta artropatia degenerativa acromioclavicular", "5314"),
    ("artroac12", "Artropatia degenerativa acromioclavicular com edema subcondral", "5333"),
    ("esporsub1", "Esporão subacromial com impressão sobre o supraespinhal", "4751"),
    ("acromplast1", "Remodelação da cortical inferior do acrômio por acromioplastia", "5310"),
    ("acromplast2", "Retificação da cortical inferior do acrômio distal", "5311"),
    ("acromplast3", "Remodelação da cortical do acrômio distal por acromioplastia", "5330"),
    ("acromplast4", "Irregularidade da cortical do acrômio por acromioplastia pregressa", "5336"),
    ("osacromiale1", "Presença de os acromiale", "4741"),
    ("luxac1", "Luxação acromioclavicular recente", "4895"),
    ("luxac2", "Sequela de lesão dos ligamentos acromioclaviculares e coracoclaviculares", "4902"),
    ("luxac3", "Rotura parcial capsuloligamentar acromioclavicular pós-traumática", "5248"),
    ("coracoclav1", "Ligamentos coracoclaviculares sem lesão", "5256"),
    ("trapezio1", "Edema pós-estiramento do trapézio na clavícula distal", "5253"),

    # ---- glenoumeral: cartilagem, osso, lábio, cápsula ----
    ("artroglen1", "Leve artropatia degenerativa glenoumeral", "4754"),
    ("artroglen2", "Artropatia degenerativa glenoumeral com osteófitos marginais", "4755"),
    ("artroglen3", "Artropatia glenoumeral acentuada com corpos osteocondrais (Milwaukee)", "4918"),
    ("artroglen4", "Artropatia glenoumeral com elevação da cabeça umeral", "5339"),
    ("cistotub1", "Alterações císticas subcorticais na tuberosidade maior", "4758"),
    ("cistotub2", "Cistos subcorticais nas tuberosidades maior e menor", "4759"),
    ("migrasup1", "Migração superior da cabeça umeral", "4948"),
    ("migrasup2", "Elevação da cabeça umeral com neoarticulação acromioumeral", "4949"),
    ("labroglen1", "Alteração degenerativa do lábio glenoidal superior e anterossuperior", "4846"),
    ("labroglen2", "Alteração degenerativa do lábio glenoidal na base do segmento superior", "4847"),
    ("labroglen3", "Alteração degenerativa do lábio com redução volumétrica anterior", "4848"),
    ("labroglen4", "Lesão de Bankart crônica e complexo de Buford", "4849"),
    ("labroglen5", "Rotura com destacamento do lábio ântero-inferior", "5060"),
    ("labroglen6", "Rotura na base dos segmentos anterior e ântero-inferior do lábio", "5061"),
    ("labroglen7", "Alteração fibrocicatricial do lábio posterior com rotura", "5189"),
    ("labroglen8", "Rotura do lábio posterior com avulsão capsuloperiosteal", "5196"),
    ("labroglen9", "Fissura na base do lábio glenoidal ântero-inferior", "5199"),
    ("labroglen10", "Rotura do lábio na base do segmento anterossuperior e superior", "5262"),
    ("labroglen11", "Alteração degenerativa do lábio superior e ântero-superior", "5372"),
    ("condralglen1", "Afilamento condral da margem anterior e ântero-inferior da glenoide", "5064"),
    ("condralglen2", "Afilamento condral glenoumeral com cistos subcondrais", "5065"),
    ("condralglen3", "Afilamento condral do rebordo posterior da glenoide", "5192"),
    ("condralglen4", "Afilamento condral do bordo anterior da cabeça umeral", "5209"),
    ("condralglen5", "Discreto afilamento condral da porção inferior da cabeça umeral", "5386"),
    ("ligglen1", "Espessamento fibrocicatricial do ligamento glenoumeral inferior", "5068"),
    ("ligglen2", "Espessamento crônico dos ligamentos glenoumerais inferiores", "5069"),
    ("capsulad1", "Leve espessamento crônico capsuloligamentar glenoumeral", "4854"),
    ("capsulad2", "Espessamento capsuloligamentar glenoumeral pós-traumático", "4855"),
    ("capsulad3", "Capsulite — espessamento capsuloligamentar difuso", "4856"),
    ("capsulad4", "Capsulite adesiva — espessamento no recesso axilar", "4857"),
    ("capsulad5", "Capsulite adesiva — alteração pericapsular no recesso inferior", "4858"),
    ("capsula1", "Alteração pós-estiramento da cápsula no recesso axilar", "5264"),

    # ---- bursa / derrame ----
    ("bursasub1", "Mínima bursite subacromial", "4678"),
    ("bursasub2", "Sinais de bursite subacromial/subdeltoidea", "4681"),
    ("bursasub3", "Edema da gordura subacromial sem bursite", "4684"),
    ("bursasub4", "Pequena bursite subacromial/subdeltoidea", "4840"),
    ("bursasub5", "Discreta distensão líquida da bursa subacromial-subdeltóidea", "4841"),
    ("bursasub6", "Distensão da bursa comunicando-se com o espaço articular", "4988"),
    ("bursasub7", "Bursite subacromial/subdeltoidea", "4995"),
    ("bursasub8", "Sem bursite subacromial-subdeltóidea significativa", "5088"),
    ("bursasub9", "Lâmina líquida na bursa subacromial-subdeltóidea", "5342"),
    ("calcmigr1", "Tendinopatia calcária migrada para a bursa com bursite", "4884"),
    ("geiser1", "Cisto artrossinovial acromioclavicular (sinal do Geyser)", "4890"),
    ("derramegle1", "Pequeno derrame com sinovite em contato com a bursa", "4863"),
    ("derramegle2", "Pequeno derrame articular glenoumeral", "4991"),
    ("derramegle3", "Pequeno derrame glenoumeral em contato com a bursa pelas rupturas", "5007"),
    ("derramegle4", "Pequeno derrame glenoumeral com sinovite reacional", "5092"),
    ("derramegle8", "Pequeno derrame articular com discreta sinovite reacional", "5275"),
    ("derramegle5", "Derrame glenoumeral com componente hemático", "5206"),
    ("derramegle6", "Mínimo derrame articular com sinovite reacional", "5269"),

    # ---- ventres musculares ----
    ("goutallier1", "Lipossubstituição do supra e infraespinhal (Goutallier II)", "4831"),
    ("goutallier2", "Atrofia e lipossubstituição por provável denervação (máscara)", "4832"),
    ("goutallier3", "Lipossubstituição do ventre muscular do redondo menor (Goutallier I)", "5366"),
    ("redondonl1", "Tendões do redondo menor e cabo longo do bíceps normais", "4827"),
    ("deltoide1", "Edema pós-traumático das fibras laterais do deltoide", "5270"),
    ("deltoide2", "Alterações cicatriciais do deltoide pós-cirúrgicas", "5395"),

    # ---- instabilidade ----
    ("hillsachs4", "Lesão de Hill-Sachs — fratura impactada póstero-superior", "5024"),
    ("hillsachs5", "Pequena lesão de Hill-Sachs sem fragmento destacado", "5037"),
    ("hillsachs6", "Sequela de lesão de Hill-Sachs", "5040"),
    ("hillsachs7", "Medidas de glenoid track e intervalo de Hill-Sachs (on/off-track)", "5046,5049,5053", "flat"),
    ("hillsachs8", "Irregularidade posterossuperior crônica da cabeça umeral", "5273"),
    ("hillsrev1", "Hill-Sachs reverso — impactação ântero-superior medial", "5171"),
    ("hillsrev2", "Sequela de Hill-Sachs reverso", "5174"),
    ("bankart1", "Impactação ântero-inferior da glenoide com rotura labral", "5027"),
    ("bankart2", "Fratura da margem ântero-inferior da glenoide com perda de 20%", "5043"),
    ("bankart3", "Fratura da glenoide ântero-inferior com destacamento labral", "341"),
    ("bankartrev1", "Bankart reverso — impactação da margem posterior da glenoide", "5181"),
    ("luxinvet1", "Luxação inveterada posterior glenoumeral", "5166"),
    ("estadinst1", "Conclusão — estadiamento de instabilidade glenoumeral", "5103"),
    ("fxtuberc1", "Fratura com impactação da tuberosidade maior umeral", "340"),
    ("fxtuberc2", "Fratura da tuberosidade maior com tendinopatia do supraespinhal", "5240"),
    ("traumaomb1", "Conclusão — alterações pós-traumáticas do ombro", "5280"),

    # ---- pós-operatório ----
    ("ancora1", "Âncoras metálicas de fixação tendínea na cabeça umeral", "5300"),
    ("ancora2", "Trajeto de âncoras no tubérculo maior umeral", "5317"),
    ("ancora3", "Irregularidade cortical e artefatos na tuberosidade maior", "5345"),
    ("ancora4", "Âncoras na glenoide — avaliação de posicionamento por TC", "5375-5376", "flat"),
    ("ancora5", "Âncoras no bordo anteroinferior e anterior da glenoide", "5377", "bullet"),
    ("posopomb1", "Irregularidade das fibras do manguito habitual no pós-operatório", "5320"),
    ("rerotura1", "Rerrotura completa do supraespinhal com retração de 4,1 cm", "5327"),
    ("rerotura2", "Rerrotura com ossificação intratendínea e retração", "5348"),

    ("tendnl1", "Tendões do subespinhal e redondo menor de aspecto normal", "5260"),
    # ---- laudos completos ----
    ("rmombro2", "RM de ombro — modelo com alternativas (AC, bursa, lábio)", "4645-4707"),
    ("rmombro3", "RM dos ombros — admissional, bilateral normal", "4541-4629"),
    ("rmombro4", "RM de ombro — modelo mestre com todas as variantes", "4728-4873 !4818"),
    ("rmombro5", "RM de ombro — rotura maciça do manguito rotador", "4922-5017"),
    ("rmombro6", "RM de ombro — instabilidade / Hill-Sachs", "5030-5103"),
    ("rmombro7", "RM de ombro — Hill-Sachs reverso / luxação posterior", "5152-5233 !5193"),
    ("rmombro8", "RM de ombro — pós-operatório de manguito rotador", "5300-5401"),
    ("rmombro9", "RM de ombro — modelo mestre com alternativas (Relatório/I.D.)", "5412-5435"),
    ("rmombro10", "RM de ombro — instabilidade (modelo Relatório/I.D.)", "5442-5468"),
    ("rmombro11", "RM de ombro — ruptura maciça (modelo Relatório/I.D.)", "5472-5496"),
    ("rmombro12", "RM de ombro — tendinopatia do manguito (modelo Relatório/I.D.)", "5501-5529"),
    ("rmombro13", "RM de ombro — capsulite adesiva com roturas parciais", "11739-11765"),
    ("rmombro14", "RM de ombro — pós-operatório de manguito com âncoras", "33-59"),
    ("rmombro15", "RM de ombro — sobrecarga da acromioclavicular", "274-299"),
    ("rmombro16", "RM de ombro — tendinopatia do manguito com comparação", "665-690"),
    ("rmombro17", "RM de ombro — edema da clavícula distal e fissuras insercionais", "702-722"),
    ("tcombro", "TC de ombro — pós-osteossíntese do úmero proximal", "12114-12139"),
    ("tcombro2", "TC de ombro — osteossíntese não consolidada", "12140-12162"),
    ("tcombro3", "TC de ombro — tendinopatia calcária do supraespinhal", "10005-10046"),
    ("tcombro4", "TC de ombro — fratura cominutiva do colo umeral", "9973-9995"),
    ("usombro", "US de ombro — rotura extensa do manguito e do cabo longo", "11177-11194"),
    ("usombro2", "US de ombro — rotura transfixante com retração e Goutallier III", "11197-11212"),
]
