# Punho, mão e dedos
ENTRADAS = [
    ("#", "PUNHO / MÃO / DEDOS"),

    # ---- fibrocartilagem triangular ----
    ("fct1", "Roturas intrassubstanciais periféricas da fibrocartilagem triangular", "4352"),
    ("fct2", "Afilamento degenerativo da porção central da fibrocartilagem triangular", "6822"),
    ("fct3", "Alteração pós-contusional da inserção ulnar da fibrocartilagem", "6824"),
    ("fct4", "Sem lesões perfurativas na fibrocartilagem triangular", "6827"),
    ("fct5", "Alteração degenerativa da inserção ulnar da fibrocartilagem", "6828"),
    ("fct6", "Alteração degenerativa da fibrocartilagem com fissura intrassubstancial", "6829"),
    ("fct7", "Afilamento das fibras centrais com tênue perfuração", "6830"),
    ("fct8", "Alteração degenerativa da fibrocartilagem com fissura longitudinal", "6831", "bullet"),
    ("fct9", "Desinserção parcial de alto grau da fibrocartilagem triangular", "6835", "bullet"),
    ("fct10", "Rotura da fibrocartilagem com indefinição da inserção na fóvea", "6841", "bullet"),
    ("fct11", "Rotura transfixante junto à inserção radial da fibrocartilagem", "6842", "bullet"),
    ("fct12", "Complexo da fibrocartilagem macerado com rotura da inserção ulnar", "6843", "bullet"),
    ("fct13", "Alteração degenerativa difusa com sinovite das lâminas ulnares", "6849"),
    ("fct14", "Rotura completa da região central da fibrocartilagem com sinovite", "6972"),
    ("fct16", "Degeneração do disco central e das inserções ulnares", "11870"),
    ("fct17", "Alteração degenerativa dos componentes ulnares foveal e estiloideo", "11899"),
    ("fct18", "Lesão parcial do disco central/porção radial da fibrocartilagem", "11900"),
    ("fct19", "Perfuração focal do disco articular da fibrocartilagem", "11991", "bullet"),

    # ---- impacto ulnocárpico / instabilidade carpal ----
    ("ulnocarp1", "Impacto ulnocárpico inicial — edema subcondral do semilunar", "6859"),
    ("ulnocarp2", "Impacto ulnocárpico — afilamento condral do semilunar", "6860"),
    ("ulnocarp3", "Impacto ulnocárpico — edema do estiloide ulnar e cisto no piramidal", "6863"),
    ("disi1", "Rotura ampla do escafossemilunar com diástase e DISI", "7033"),
    ("disi2", "Degeneração do escafossemilunar com instabilidade em DISI", "7036"),
    ("disi3", "Lesão do escafossemilunar com diástase e DISI", "7037"),
    ("disi4", "Conclusão — alteração crônica do escafossemilunar com DISI", "7106"),
    ("disi5", "Diástase escafossemilunar com flexão volar do escafoide", "10633"),
    ("escafosem1", "Rotura extensa do ligamento escafossemilunar", "7042"),
    ("escafosem2", "Rotura crônica do escafossemilunar com diástase", "7043"),
    ("escafosem3", "Degeneração da banda volar do ligamento escafossemilunar", "11844"),
    ("subluxulna1", "Subluxação dorsal da ulna em relação ao rádio", "6810"),
    ("varianteulnar1", "Variação ulnar positiva com hipoplasia da epífise do rádio", "6798"),
    ("varianteulnar2", "Encurtamento da porção medial da epífise do rádio", "6802"),

    # ---- osso e cartilagem do carpo ----
    ("kienbock1", "Doença de Kienböck — edema difuso do semilunar", "6807"),
    ("kienbock2", "Edema do semilunar — sobrecarga x osteonecrose inicial", "6994"),
    ("kienbock3", "Condropatia do semilunar com esclerose e cistos", "11867"),
    ("kienbock4", "Edema medular difuso do semilunar com cistos subcondrais", "11894"),
    ("semilunar2", "Semilunar tipo II com impacto no polo proximal do hamato", "11895"),
    ("artroradio1", "Artropatia degenerativa radioescafoide", "6777"),
    ("artroradio2", "Artropatia degenerativa radiocarpal e mediocarpal", "6780-6781", "flat"),
    ("condroradio1", "Condropatia da epífise distal do rádio", "6782", "bullet"),
    ("condrocapitato1", "Condropatia do polo proximal do capitato e do hamato", "11868"),
    ("artromediocarp1", "Afilamento condral das mediocárpicas com sinovite", "11841"),
    ("artrometacarpo1", "Afilamento condral da base do segundo metacarpo", "11842"),
    ("artroradioulnar1", "Artropatia degenerativa radioulnar distal", "11984", "bullet"),
    ("artrocarpo1", "Afilamento condral difuso radiocárpico e mediocárpico", "6795"),
    ("cistocarpo1", "Cistos subcorticais no semilunar e no piramidal", "6785", "bullet"),
    ("cistocarpo2", "Alterações císticas no capitato e hamato, semilunar tipo II", "6786", "bullet"),
    ("cistometacarpo1", "Cistos subcondrais na base do II metacarpo", "11898"),
    ("pisopiram1", "Artropatia pisopiramidal", "11897"),
    ("edemaradio1", "Foco de edema ósseo junto ao tubérculo de Lister", "6774", "bullet"),
    ("encondromacapitato1", "Lesão de provável natureza condral no capitato (encondroma)", "11903"),
    ("osteofitostrapezio1", "Esboços osteofitários trapézio-metacárpicos", "11985", "bullet"),
    ("osteossintradio1", "Osteossíntese do rádio distal com placa volar", "11866"),

    # ---- rizartrose ----
    ("rizart1", "Discreta rizartrose com espessamento capsuloligamentar", "4351"),
    ("rizart2", "Leve rizartrose com esboços osteofitários", "6789"),
    ("rizart3", "Rizartrose com derrame articular e sinovite", "6790"),
    ("rizart4", "Afilamento condral trapeziometacarpal", "6791"),
    ("rizart5", "Mínimo afilamento condral entre o trapézio e a base do I metatarso (sic)", "6792"),
    ("rizart6", "Rizartrose incipiente com pequeno derrame articular", "11843"),
    ("rizart7", "Derrame na trapézio-metacarpal com espessamento capsuloligamentar", "11901"),
    ("rizart8", "US — leve rizartrose", "11228"),

    # ---- tendões e bainhas ----
    ("tenossinext1", "Tenossinovite dos compartimentos extensores com realce", "4349"),
    ("tenossinext2", "Tenossinovite do I e II compartimentos extensores", "6875"),
    ("tenossinext3", "Tendinopatia e tenossinovite do I e VI compartimentos", "6876"),
    ("tenossinext4", "Tendinopatia e tenossinovite do I compartimento com fissuras", "6877"),
    ("tenossinext5", "US — tendinopatia do I compartimento extensor com tenossinovite", "11237"),
    ("quervain1", "Tendinopatia do I compartimento extensor (De Quervain)", "6878", "bullet"),
    ("interseccao1", "Síndrome da intersecção do antebraço distal", "6888"),
    ("tenossinflex1", "Distensão líquida da bainha dos flexores no túnel do carpo", "4348"),
    ("tenossinflex2", "Realce ao redor dos flexores nas metacarpofalângicas", "981"),
    ("tenossinflex3", "Tenossinovite dos flexores dos dedos", "6884"),
    ("tenossinflex4", "Tenossinovite do flexor radial longo do carpo", "6885"),
    ("flexoruln1", "Peritendinite insercional do flexor ulnar do carpo", "4350"),
    ("eucarpo1", "Tendinopatia do extensor ulnar do carpo", "11846"),
    ("eucarpo2", "Tendinopatia e tenossinovite do extensor ulnar do carpo", "11902"),
    ("eucarpo3", "Tendinopatia do sexto compartimento extensor", "11993"),
    ("bursasflex1", "Alterações inflamatórias das bursas radial e ulnar dos flexores", "11992", "bullet"),
    ("tenossininf1", "Tenossinovite infecciosa dos extensores com coleção", "6951"),

    # ---- nervo mediano / túnel do carpo ----
    ("nervomediano1", "Nervo mediano e canal de Guyon sem alterações", "6896"),
    ("nervomediano2", "Nervo mediano bífido com artéria mediana persistente", "6897"),
    ("nervomediano3", "Nervo mediano espessado no túnel do carpo", "6900"),
    ("nervomediano4", "Edema do nervo mediano na entrada do túnel do carpo", "6903"),
    ("nervomediano5", "Alteração fibrocicatricial pós-cirúrgica do retináculo dos flexores", "6912"),
    ("nervomediano6", "Espessamento e alteração de sinal do nervo mediano", "11995", "bullet"),
    ("nervomediano7", "US — nervo mediano bífido no limite superior da normalidade", "11274"),
    ("tunelcarpo1", "Conclusão — achados de síndrome do túnel do carpo", "12002", "bullet"),
    ("posoppunho1", "Alterações fibrocicatriciais volares com descontinuidade do retináculo", "6871"),

    # ---- derrame, cistos, artropatia inflamatória ----
    ("sinovitepunho1", "Sinovite pancompartimental do punho com realce", "4346"),
    ("sinovitepunho2", "Derrame radioulnar distal e radiocárpico com sinovite", "6923"),
    ("sinovitededos1", "Derrame nas metacarpofalângicas e interfalângicas com sinovite", "4347"),
    ("cistopunho1", "Formação cística volar comunicante com o radiocárpico", "6928"),
    ("cistopunho2", "Formação cística artrossinovial volar radiocárpica", "7088"),
    ("cistopunho3", "US — formação cística volar radiocárpica", "11234"),
    ("cistoroto1", "Cisto artrossinovial roto — edema distal à pisopiramidal", "6988"),
    ("cistoroto2", "Cisto artrossinovial roto — líquido radiocárpico volar", "6989", "bullet"),
    ("cistoroto3", "Cisto artrossinovial roto — edema dorsal do carpo", "6990", "bullet"),
    ("arpunho1", "Artrite reumatoide — sinovite proliferativa pancompartimental", "6967"),
    ("arpunho2", "Artrite reumatoide — tenossinovite dos extensores e bursas carpais", "6968"),
    ("arpunho3", "Tenossinovite do flexor longo do polegar e flexor radial do carpo", "6969"),
    ("ligpunho1", "Ligamentos intrínsecos e extrínsecos espessados", "6974"),
    ("artriteerosiva1", "Artropatia inflamatória erosiva das interfalangianas em atividade", "975"),
    ("trapezomcp1", "Artropatia inflamatória trapézio-metacarpal em atividade", "977"),
    ("progressaoar1", "Progressão da artropatia inflamatória com aumento da sinovite", "991"),

    # ---- dedos: polia, placa volar, dedo em gatilho ----
    ("gatilho1", "Dedo em gatilho — tenossinovite dos flexores e polia A1", "4279"),
    ("gatilho2", "Conclusão — dedo em gatilho", "4285", "bullet"),
    ("gatilho3", "Espessamento da polia A1 do terceiro dedo com tenossinovite", "4288"),
    ("gatilho4", "Tenossinovite estenosante da polia A1 do terceiro dedo", "4293", "bullet"),
    ("gatilho5", "Dedo em gatilho do polegar — flexor longo e polia A1", "4298", "bullet"),
    ("placavolar1", "Rotura da placa volar da interfalangiana do polegar", "4367"),
    ("placavolar2", "Lesão da placa volar da terceira metacarpofalângica", "11801"),
    ("artromcf1", "Artropatia degenerativa da terceira metacarpofalângica", "11800"),
    ("artrodedos1", "Alterações degenerativas das metacarpofalângicas e interfalangeanas", "4315", "bullet"),

    # ---- polegar ----
    ("fxpolegar1", "Fratura incompleta da falange proximal do polegar", "4365"),
    ("derramepoleg1", "Derrame na interfalangiana do polegar pós-traumático", "4366"),
    ("derramepoleg2", "Derrame na metacarpofalângica do polegar pós-traumático", "4394"),
    ("poliapoleg1", "Rotura das polias A2 e oblíqua do polegar", "4368"),
    ("colatpoleg1", "Edema periligamentar dos colaterais da interfalangiana", "4369"),
    ("flexpoleg1", "Tenossinovite do flexor longo do polegar pós-traumática", "4370"),
    ("flexpoleg2", "Tenossinovite do flexor longo do polegar sem lesão tendínea", "4396"),
    ("extpoleg1", "Estiramento do aparelho extensor do polegar", "4371"),
    ("extpoleg2", "Estiramento do extensor do polegar na metacarpofalângica", "4398"),
    ("ucpolegar1", "Rotura com desinserção do colateral ulnar da MCF do polegar", "4392"),
    ("ucpolegar2", "Rotura com desinserção do colateral radial da MCF do polegar", "4393"),
    ("ucpolegar3", "Conclusão — rotura capsuloligamentar da MCF do polegar", "4405"),
    ("subluxpoleg1", "Subluxação volar da base da falange proximal do polegar", "4395"),
    ("capspoleg1", "Irregularidade capsuloligamentar dorsal da MCF do polegar", "4397"),
    ("stener1", "Lesão de Stener — rotura do colateral ulnar com aponeurose interposta", "4449"),

    # ---- fáscia palmar / tumores ----
    ("dupuytren1", "Fibromatose palmar (Dupuytren) — espessamento da fáscia palmar", "4314"),
    ("dupuytren2", "Conclusão — fibromatose palmar (Dupuytren)", "4325", "bullet"),
    ("fascpalmar1", "Alteração fibrocicatricial da face volar (rascunho da autora, com dúvida e sem pontuação final)", "861"),
    ("atitudeflex1", "Atitude em flexão das metacarpofalangeanas", "4312"),
    ("atitudeflex2", "Atitude em flexão da interfalangeana proximal do quinto dedo", "4313"),
    ("fibromatpalm1", "US — nódulo palmar compatível com fibromatose", "11171"),
    ("pacini1", "Proeminência dos corpúsculos de Pacini no subcutâneo", "4258"),
    ("pacini2", "Discreta proeminência dos corpúsculos de Pacini", "4264"),
    ("tcgbainha1", "Nódulo junto à bainha dos flexores — tumor de células gigantes", "4504-4505", "unir"),
    ("tcgbainha2", "Tumor de células gigantes de bainha tendínea", "4509"),
    ("tcgbainha3", "Conclusão — tumor de células gigantes de bainha tendínea", "4515"),
    ("schwannomamao1", "Lesão dorsoulnar do polegar — schwannoma x TCG", "4459"),
    ("schwannomamao2", "Conclusão — lesão de linhagem neural no polegar", "4463"),
    ("hemangmao1", "Hemangioma / malformação vascular da mão", "4491"),
    ("hemangmao2", "Hemangioma dos planos musculoadiposos da mão", "12405"),
    ("hemangmao3", "Lesão vascular benigna dos espaços interdigitais", "12424"),

    # ---- fraturas do carpo (TC) ----
    ("fxescafoide1", "Fratura completa do terço médio do escafoide", "10594"),
    ("fxsemilunar1", "Fratura cominutiva da face volar do semilunar", "10597"),
    ("fxpiramidal1", "Fratura cominutiva do terço distal do piramidal", "10598"),
    ("fxhamato1", "Fratura do hâmulo do hamato", "10632"),

    ("miotendinpunhonl1", "Demais estruturas musculotendíneas com morfologia e sinal preservados", "4354"),
    ("ligpunhonl1", "Estruturas ligamentares intrínsecas e extrínsecas do punho normais", "4355"),
    ("ligcarponl1", "Ligamentos intrínsecos e extrínsecos do carpo de aspecto normal", "6818"),
    ("cistopunho4", "US — formação cística volar radiocárpica artrossinovial", "11256"),
    ("tenossinext6", "US — leve tenossinovite dos compartimentos extensores", "11262"),
    ("tenossinext7", "US — leve tendinopatia do I compartimento extensor", "11259"),
    # ---- laudos completos ----
    ("rmpunho2", "RM de punho — normal", "6684-6729"),
    ("rmpunho3", "RM de punho — modelo mestre com DISI", "7001-7106 !7032,7056,7069"),
    ("rmpunho4", "RM de punho — artropatia mediocárpica e degeneração da fibrocartilagem", "11835-11859"),
    ("rmpunho5", "RM de punho — pós-osteossíntese do rádio com Kienböck", "11860-11886"),
    ("rmpunho6", "RM de punho — edema do semilunar e alterações mecânicas", "11890-11921"),
    ("rmpunho7", "RM de punho — síndrome do túnel do carpo", "11980-12003"),
    ("rmmao2", "RM de mão — normal", "4207-4252"),
    ("rmmao3", "RM de mão — fibromatose palmar (Dupuytren)", "4306-4328"),
    ("rmmao4", "RM de polegar — rotura capsuloligamentar da metacarpofalângica", "4382-4405"),
    ("rmmao5", "RM de mão — hemangioma em criança", "4481-4491"),
    ("rmmao6", "RM de mão — artropatia da terceira metacarpofalângica", "11794-11810"),
    ("rmmao7", "RM de mão — hemangioma intramuscular", "12392-12413"),
    ("rmmao8", "RM de mão — controle de lesão vascular pós-ressecção", "12418-12434"),
    ("rmmao9", "RM de mão — artropatia inflamatória em atividade", "966-991"),
    ("tcpunho", "TC de mão — artropatia infecciosa", "10554-10584"),
    ("tcpunho2", "TC de punho — fraturas do carpo", "10588-10619"),
    ("tcpunho3", "TC de punho — controle pós-cirúrgico com fios de Kirchner", "10620-10641"),
    ("uspunho", "US de mão e punho — rizartrose e cisto artrossinovial", "11224-11253"),
    ("uspunho2", "US de mão e punho — rizartrose e nervo mediano bífido", "11267-11288"),
    ("usmao", "US de partes moles — fibromatose palmar", "11165-11176"),
]
