# Quadril, bacia e sínfise púbica
ENTRADAS = [
    ("#", "QUADRIL / BACIA / SÍNFISE PÚBICA"),

    # ---- morfologia femoroacetabular ----
    ("displasiaacet1", "Displasia acetabular com verticalização do teto", "7225"),
    ("coxavalga1", "Coxa valga com aumento do ângulo cervicodiafisário", "7230"),
    ("remodelcabeca1", "Remodelamento da porção superior da cabeça femoral", "7235"),
    ("camfemoral1", "Proeminência ântero-lateral da transição cabeça/colo (CAM)", "7262"),
    ("camfemoral2", "Proeminência da transição cabeça/colo com cisto subcortical", "7263"),
    ("camfemoral3", "Perda do acinturamento da transição cabeça/colo femoral", "7264"),
    ("camfemoral4", "Proeminência ântero-superior predispondo a impacto tipo CAM", "7265"),
    ("camfemoral5", "Perda da concavidade da transição cabeça/colo femoral", "10117"),
    ("pincer1", "Acetábulo profundo com ampla cobertura da cabeça femoral", "7266"),
    ("hipertrofnl1", "Sem hipertrofia óssea na cabeça e colo femoral", "7148"),
    ("retroversaoacet1", "Retroversão acetabular cranial", "10188"),
    ("anguloalfa1", "Transição cabeça/colo preservada com ângulo alfa normal", "10189"),

    # ---- cartilagem, lábio, ligamento redondo ----
    ("artroquadril1", "Leve artropatia degenerativa do quadril", "7244"),
    ("artroquadril2", "Artropatia degenerativa acentuada com sequela de fratura subcondral", "7247"),
    ("artroquadril3", "TC — alterações degenerativas superolaterais dos quadris", "10108"),
    ("artroquadril4", "TC — alterações degenerativas com redução difusa do espaço", "10109"),
    ("artroquadril5", "TC — artropatia degenerativa com osteófitos circunferenciais", "10190"),
    ("artromicrocrist1", "Artropatia microcristalina x degenerativa do quadril", "10157"),
    ("condralquadrilnl1", "Superfícies condrais femoroacetabulares preservadas", "7255"),
    ("cistoacet1", "Formação cística com insinuação sinovial no teto acetabular", "7250"),
    ("tetoacet1", "Reação osteo-hipertrófica marginal no teto acetabular", "10119"),
    ("edemaacet1", "Tênue edema ósseo súpero-lateral do acetábulo", "8319"),
    ("labroacet1", "Alteração degenerativa do lábio acetabular ântero-superior", "7270"),
    ("labroacet2", "Rotura na base do lábio acetabular ântero-superior", "7271"),
    ("labroacet3", "Ossificação na base do lábio póstero-superior", "7272"),
    ("ligredondo1", "Indefinição do ligamento redondo por rotura crônica", "7277"),
    ("ligredondo2", "Afilamento degenerativo do ligamento redondo com osteófitos", "7278"),
    ("ligredondo3", "Degeneração e afilamento do ligamento redondo", "7279"),
    ("iliofemoral1", "Espessamento crônico do ligamento iliofemoral", "7280"),
    ("hernsinovial1", "Herniação sinovial da transição cabeça/colo femoral", "10150"),

    # ---- tendões periarticulares ----
    ("gluteomin1", "Tendinopatia e peritendinite dos glúteos médio e mínimo", "7290"),
    ("gluteomin2", "Tendinopatia dos glúteos médio e mínimo bilateral", "7291"),
    ("gluteomin3", "Rotura parcial do glúteo mínimo com bursite subglútea", "7292"),
    ("gluteomin4", "Tendinopatia calcária do glúteo médio em fase expulsiva", "7293"),
    ("isquiotib1", "Leve tendinopatia e peritendinite dos isquiotibiais", "7171"),
    ("isquiotib2", "Tendinopatia e peritendinite da origem do semimembranoso", "7296"),
    ("isquiotib3", "Tendinopatia e peritendinite da origem dos isquiotibiais", "7297"),
    ("isquiotib4", "Tendinopatia na origem dos isquiotibiais com espessamento", "7298"),
    ("isquiotib5", "Leve tendinopatia na origem dos isquiotibiais", "7299"),
    ("isquiotib6", "Rotura parcial extensa da origem dos isquiotibiais", "7305"),
    ("tendsemimb1", "Tendinopatia do semimembranoso na tuberosidade isquiática", "7159"),
    ("bursasemimb1", "Mínima bursite isquioglútea", "7157"),
    ("bursatroc1", "Sem evidência de bursite trocantérica", "7173"),
    ("retofem1", "Sequela de rotura extensa do reto femoral com retração", "7335"),
    ("adutorlongo1", "Rotura com desinserção da origem do adutor longo", "7406"),
    ("adutorlongo2", "Rotura do adutor longo com retração de 1,8 cm", "7407"),
    ("adutorlongo3", "Rotura do adutor longo com extensão à aponeurose retoadutora", "7408"),
    ("adutorlongo4", "Tendinopatia com fissura do adutor longo", "8317"),
    ("retoadutora1", "Rotura fina da aponeurose retoadutora", "8268"),
    ("retoadutora2", "Conclusão — rotura da aponeurose retoadutora", "8274"),
    ("retoadutora3", "Irregularidade com edema da aponeurose retoadutora", "8318"),

    # ---- atritos e impactos extra-articulares ----
    ("isquiofem1", "Impacto isquiofemoral — tênue edema do quadrado femoral", "7318"),
    ("isquiofem2", "Impacto isquiofemoral bilateral do quadrado femoral", "7319"),
    ("isquiofem3", "Alteração do quadrado femoral por hipersolicitação mecânica", "7320"),
    ("iliotibial1", "Edema do plano adiposo entre trocânter maior e trato iliotibial", "7323"),
    ("iliotibial2", "Edema da gordura peritrocantérica por atrito", "7324"),
    ("iliotibial3", "Edema da gordura do trato iliotibial com bolsa trocantérica", "7325"),
    ("iliotibial4", "Leve edema da gordura do trato iliotibial", "7326"),
    ("iliotibial5", "Peritendinite da origem do trato iliotibial na crista ilíaca", "7332"),

    # ---- sínfise púbica e sacroilíacas (mecânico) ----
    ("sinfise1", "Artropatia degenerativa da sínfise púbica", "7353"),
    ("sinfise2", "Osteófitos da sínfise púbica com tênue edema subcondral", "7354"),
    ("sinfise3", "Reação osteofitária marginal da sínfise púbica", "7355"),
    ("sinfise4", "Reação osteo-hipertrófica da sínfise púbica (sinfisite)", "8267"),
    ("sinfise5", "Conclusão — sinfisite púbica", "8273"),
    ("sinfise6", "TC — irregularidade e esclerose da sínfise púbica", "10192"),
    ("pubeite1", "Osteíte / sinfisite púbica de origem mecânica", "7412"),
    ("pubeite2", "Edema ósseo do púbis estendendo-se aos ramos púbicos", "7415"),
    ("pubeite3", "Artropatia da sínfise púbica com osteíte púbica", "8316"),
    ("avulsaopubis1", "Fratura avulsiva do púbis junto à origem do adutor longo", "8281"),
    ("artrosacro1", "Artropatia degenerativa da sacroilíaca de natureza mecânica", "7360"),
    ("artrosacro2", "TC — alterações degenerativas das sacroilíacas e sínfise", "10111"),
    ("artrosacro3", "TC — sacroilíacas com pneumatocisto intraósseo", "10112"),
    ("artrosacro4", "TC — sacroilíaca com fenômeno de vácuo", "10159"),
    ("entesofitos1", "Entesófitos nas espinhas ilíacas, ísquios e trocânteres", "10115"),
    ("entesofitos2", "Entesófitos na espinha ilíaca, ísquio, crista e trocânter", "10193"),
    ("calcisquio1", "Calcificações nos tendões dos isquiotibiais", "10126"),
    ("calcperiacet1", "Calcificações periacetabulares", "10127"),
    ("megapofise1", "Megapófise transversa na vértebra pré-sacra", "10121"),

    # ---- osso: necrose, fraturas, lesões ----
    ("osteonecfem1", "Osteonecrose da cabeça femoral sem perda da esfericidade", "7517"),
    ("osteonecfem2", "Osteonecrose acometendo mais de 50% da superfície articular", "7518"),
    ("osteonecfem3", "Osteonecrose extensa com colapso e descompressão cirúrgica", "7528", "bullet"),
    ("osteonecfem4", "Osteonecrose extensa da cabeça femoral com impactação", "994", "bullet"),
    ("fxsubcondral1", "Fratura subcondral da cabeça femoral", "7519"),
    ("fxcolofemur1", "Fratura completa do colo femoral com desalinhamento", "7522"),
    ("fxincompletacolo1", "TC — fratura incompleta da transição cabeça/colo", "10138"),
    ("fxtranstroc1", "TC — fratura transtrocantérica sem desalinhamento", "10097"),
    ("fxsubcapital1", "TC — fratura impactada subcapital", "10100"),
    ("fxtrocanter1", "TC — fratura transversa do trocânter maior", "10055"),
    ("sequelatrocanter1", "TC — deformidade do trocânter por sequela de fratura", "10105"),
    ("osteossintquadril1", "TC — osteossíntese de fratura transtrocantérica consolidada", "10095"),
    ("gammanail1", "TC — haste intramedular com pino deslizante (Gamma Nail)", "10181"),
    ("atrasoconsolid1", "TC — ausência de calo ósseo, possível atraso de consolidação", "10151"),
    ("avulsaoeiai1", "Fratura por avulsão da espinha ilíaca ântero-inferior", "7398"),
    ("avulsaoeiai2", "TC — avulsão da espinha ilíaca anteroinferior", "10102"),
    ("avulsaoeiai3", "TC — conclusão de avulsão da espinha ilíaca anteroinferior", "10103"),
    ("fxinsufsacro1", "Fratura por insuficiência da asa sacral", "7732"),
    ("fxinsufsacro2", "TC — fratura por insuficiência sacral e dos ramos púbicos", "10180"),
    ("fxacetabulo1", "TC — fratura cominutiva do teto acetabular", "10147"),
    ("fxisquiopubico1", "TC — fratura do ramo isquiopúbico em consolidação", "10148"),
    ("lesaofocalfemur1", "Lesão intertrocantérica — cisto intraósseo x lesão condral", "7388"),
    ("lesaocistica1", "Lesão cística do colo femoral sem sinais de agressividade", "7451"),
    ("lesaofemur1", "Lesão condral do fêmur proximal com necrose pregressa", "956"),
    ("lesaoacetabulo1", "TC — lesão de matriz cartilaginosa na parede acetabular", "10145"),
    ("tumorosseobaixo1", "TC — lesão lítica de baixa agressividade no colo femoral", "10135"),
    ("tumorosseobaixo2", "TC — conclusão de lesão de baixa agressividade", "10136"),
    ("metabacia1", "Acometimento secundário difuso dos ossos da bacia", "7384"),
    ("metabacia2", "Metástases da bacia com fratura patológica do cálcar femoral", "244"),
    ("paget1", "TC — espessamento cortical compatível com doença de Paget", "10069"),
    ("bifosfonado1", "Espessamento cortical femoral por bifosfonados", "1005"),
    ("osteomaosteoide1", "Edema do fêmur proximal — osteoma osteoide x infecção", "11384"),
    ("medularverm1", "Hiperplasia da medular vermelha", "7533"),
    ("infartoiliaco1", "Infartos ósseos prévios na asa ilíaca", "7534"),

    # ---- depósito, infecção, partes moles, próteses ----
    ("amiloide1", "Doença de depósito capsuloligamentar do quadril", "950"),
    ("amiloide2", "Artropatia amiloide induzida por hemodiálise", "7656"),
    ("amiloide3", "Edema dos iliopsoas e adutores por artropatia de depósito", "7659"),
    ("ulceragluteo1", "Lesão por pressão glútea com osteomielite do ramo isquiopúbico", "7445"),
    ("ulcerasacral1", "Escara de pressão trocantérica com coleção", "7742"),
    ("ulcerasacral2", "Úlcera sacral — avaliação por estudo de bacia", "7753"),
    ("osteomieliteiliaco1", "TC — osteomielite do ilíaco com solução de continuidade cutânea", "10174"),
    ("armafogo1", "Trajeto intramuscular por lesão por arma de fogo", "9001"),
    ("perdasubstancia1", "Perda de substância do colo femoral com osteonecrose", "12374"),
    ("proteseq1", "Prótese total do quadril bilateral com artefatos", "7419"),
    ("proteseq2", "Sem coleções ao redor dos componentes protéticos", "7422"),
    ("protesecimentada1", "TC — artroplastia cimentada com sinais de soltura", "10168"),
    ("implantegluteo1", "Implantes glúteos íntegros, sem coleções pericapsulares", "7652"),
    ("silicone1", "Material exógeno glúteo por procedimento estético", "7439"),
    ("lipoenxertia1", "Gordura no glúteo máximo compatível com lipoenxertia", "7394"),
    ("atrofiagluteo1", "TC — atrofia parcial da musculatura glútea", "10130"),
    ("densifsubcut1", "TC — densificação do subcutâneo adjacente ao trocânter", "10123"),
    ("coleecoxa1", "Coleção líquida/hemática peritrocantérica", "10064"),
    ("fxbacia1", "TC — fratura cominutiva do ilíaco com extensão acetabular", "10348"),
    ("fxbacia2", "TC — fratura completa do ramo isquiopúbico", "10349"),
    ("fxbacia3", "TC — fratura da asa sacral com extensão ao forame de S1", "10350"),
    ("luxquadril1", "Fratura com impactação anterior da cabeça femoral", "10270"),
    ("luxquadril2", "Fratura/avulsão da margem póstero-superior do acetábulo", "10271"),

    ("iliotibial6", "Edema da gordura entre trato iliotibial e trocânter maior", "1577"),
    ("condralacet1", "Irregularidade condral ântero-superior do acetábulo com edema", "3677"),
    ("artroquadril6", "TC — artropatia degenerativa dos quadris com esclerose do teto", "10074"),
    ("artrosacro5", "TC — artropatia da sínfise e sacroilíacas com condrocalcinose", "10075"),
    ("obsinfiltracao1", "Obs. — sugerir RM em suspeita de infiltração da medular óssea", "10092"),
    ("artroquadril7", "TC — redução do espaço articular superior com esclerose", "10146"),
    ("derramequadril1", "TC — derrame intra-articular com calcificações de permeio", "10153"),
    ("artroquadril8", "TC — artropatia do compartimento de carga do quadril", "10154"),
    ("calcligredondo1", "TC — calcificação na topografia do ligamento redondo", "10161"),
    ("cimentoprotese1", "TC — protrusão medial de cimento para a escavação pélvica", "10170"),
    ("tunelosseo1", "TC — túnel ósseo colodiafisário por retirada de osteossíntese", "10171"),
    ("retificailiaco1", "TC — retificação da asa ilíaca por manipulação cirúrgica", "10175"),
    ("obliteracaotroc1", "TC — obliteração dos planos musculares peritrocantéricos", "10176"),
    ("sequelaisquiopub1", "TC — deformidade dos ramos isquiopúbicos por sequela de fratura", "10179"),
    ("artrosacro6", "TC — artropatia da sínfise e sacroilíacas assimétrica", "10182"),
    ("artroquadril9", "TC — artropatia degenerativa incipiente do quadril", "10183"),
    ("entesofitos3", "TC — entesófitos nas tuberosidades isquiáticas e trocânteres", "10185"),
    ("artrosacro7", "TC — artropatia da sacroilíaca com esclerose do ilíaco", "10191"),
    ("miotendinnl1", "TC — estruturas musculotendíneas normais, com ressalva do método", "10194"),
    ("densifsubcut2", "TC — densificação do subcutâneo lateral do quadril", "10195"),
    ("sinfisenl1", "Demais estruturas ósseas e miotendíneas da sínfise preservadas", "8320"),
    ("entesofitos4", "TC — entesófitos nas cristas ilíacas, trocânteres e ísquios", "10076"),
    ("osseasnl1", "TC — demais estruturas ósseas preservadas, sem outras fraturas", "10077"),
    ("atrofiagluteo2", "TC — discreta hipotrofia e lipossubstituição da glútea", "10078"),
    ("atrofiagluteo3", "TC — hipotrofia com lipossubstituição parcial da glútea", "10177"),
    ("atrofiagluteo4", "TC — sem atrofia significativa dos músculos avaliados", "10129"),
    ("artrosacro8", "TC — esclerose subcondral das sacroilíacas", "10113"),
    ("artrosacro9", "TC — alterações degenerativas incipientes das sacroilíacas", "10149"),
    ("artrosacro10", "TC — alterações da sínfise e sacroilíaca esquerda", "10144"),
    ("artrosacro11", "TC — alterações da sínfise e terço inferior das sacroilíacas", "10156"),
    ("artrosacro12", "TC — alterações da sínfise e da coluna lombar", "10160"),
    ("artrosacro13", "TC — alterações da sínfise, sacroilíacas e coluna lombar", "10173"),
    ("esclerosecabeca1", "TC — esclerose subcondral das porções superiores da cabeça femoral", "10140"),
    ("tetoacet2", "TC — esclerose subcondral e osteófito no teto acetabular", "10141"),
    ("tetoacet3", "TC — reação osteo-hipertrófica no trocânter maior", "10143"),
    ("camfemoral6", "TC — retificação da porção anterior da transição cabeça/colo", "10155"),
    ("camfemoral7", "TC — discreta perda da concavidade da transição cabeça/colo", "10158"),
    ("artroquadril10", "TC — artropatia do quadril direito com esclerose do teto", "10172"),
    ("ossificacaotroc1", "TC — ossificações nas partes moles adjacentes ao trocânter", "10169"),
    ("entesofitos5", "TC — entesófito no trocânter maior e tuberosidades isquiáticas", "10178"),
    ("ossificacaofx1", "TC — diminuta ossificação superior ao traço de fratura", "10152"),
    ("granulomagluteo1", "TC — granuloma calcificado na região glútea", "10167"),
    ("fiosmetalicos1", "TC — fios metálicos na topografia do reto", "10165"),
    ("obliteracaogluteo1", "TC — obliteração do subcutâneo glúteo por edema ou hematoma", "10124"),
    ("miotendinnl2", "TC — musculotendíneas normais, com ressalva do método", "10163"),
    ("ateromatose1", "TC — ateromatose aorto-ilíaca", "10079"),
    ("bexigarepleta1", "TC — bexiga urinária em acentuada repleção", "10080"),
    ("calcvasculares1", "TC — calcificações parietais vasculares", "10132"),
    ("flebolitos1", "TC — flebólitos na escavação pélvica", "10196"),
    ("fxdesalinhadanl1", "TC — sem sinais de fratura desalinhada", "10139"),
    ("derramequadril2", "TC — pequeno derrame articular no quadril", "10142"),
    ("derramequadril3", "TC — pequeno/moderado derrame articular", "10162"),
    ("atrofiagluteo5", "TC — discreta hipotrofia da musculatura glútea", "10186"),
    # ---- laudos completos ----
    ("rmquadril2", "RM de quadril — modelo mestre com alternativas", "7132-7184"),
    ("rmquadril3", "RM de quadril — modelo mestre com alterações", "7206-7371 !7219,7222,7338"),
    ("rmquadril4", "RM de quadril — osteonecrose e fratura da cabeça femoral", "7501-7591"),
    ("rmquadril5", "RM de quadril — modelo mestre com alternativas (Relatório/I.D.)", "7674-7701"),
    ("rmquadril6", "RM de quadril — degenerativo (modelo Relatório/I.D.)", "7704-7726"),
    ("rmquadril7", "RM de quadril — artrose com tendinopatia dos glúteos", "11926-11946"),
    ("rmbacia2", "RM de bacia — controle de hemipelvectomia", "7463-7484"),
    ("rmbacia3", "RM de bacia — reconversão medular e alterações degenerativas", "12092-12112"),
    ("rmbacia4", "RM de bacia e coxa — suspeita de osteoma osteoide", "11379-11393"),
    ("rmsacro2", "RM sacrococcígea — controle pós-sacrectomia", "7781-7793"),
    ("tcquadril", "TC de quadril — estudo de artroplastia total (com referências)", "146-176"),
    ("tcquadril2", "TC de quadril — artroplastia total, modelo com medidas", "7601-7645"),
    ("tcquadril4", "TC de bacia/quadril — normal", "10243-10266"),
    ("tcquadril5", "TC de quadril — sem alterações, com ressalva de RM", "12352-12365"),
    ("tcbacia2", "TC de bacia — trauma com fratura da crista ilíaca", "10292-10344"),
    ("tcbacia3", "TC de bacia — artropatia degenerativa dos quadris e sacroilíacas", "10354-10395"),
    ("tcbacia4", "TC de bacia — fratura em livro aberto com fixador externo", "10411-10429"),
    ("tcbacia5", "TC de bacia — sequela de disjunção sacroilíaca", "10447-10468"),
    ("tcbacia6", "TC de bacia — próteses glúteas", "10484-10519"),
    ("tcbacia7", "TC de bacia — controle pós-sacrectomia", "7762-7773"),
    ("tccoxa2", "TC de coxa — formação expansiva com calcificações", "9793-9829"),
]
