# Sacroilíacas, sacrococcígea, plexos e desfiladeiro torácico
ENTRADAS = [
    ("#", "SACROILÍACAS / SACROCOCCÍGEA"),

    ("sacroiliaca1", "Leve esclerose subcondral das sacroilíacas por sobrecarga", "66", "bullet"),
    ("sacroiliaca2", "Focos de edema ósseo subcondral na face sacral", "74", "bullet"),
    ("sacroiliaca3", "Conclusão — focos de edema subcondral inespecíficos", "82"),
    ("sacroiliaca4", "Sacroilíaca com erosões e realce — afastar origem inflamatória", "8009"),
    ("sacroiliaca5", "Edema subcondral do componente ilíaco, de provável natureza mecânica", "8013"),
    ("sacroiliaca6", "Artropatia degenerativa da porção sinovial da sacroilíaca", "8015"),
    ("sacroiliaca7", "Edema ósseo sacroilíaco e púbico relacionado ao pós-parto", "8021"),
    ("sacroiliaca8", "Edema da porção posterior da sacroilíaca — entesite", "8065"),
    ("sacroiliaca9", "Irregularidade cortical do componente ilíaco com edema subcondral", "8202"),
    ("sacroiliaca10", "Irregularidade cortical do ilíaco sem edema significativo", "8205"),
    ("sacroiliaca12", "Conclusão — irregularidade cortical à esquerda sem edema", "8231"),
    ("sacroiliaca13", "Conclusão — achados inespecíficos com história de artropatia inflamatória", "8234"),
    ("sacroiliite1", "Sacroileíte de provável etiologia inflamatória em atividade", "8142"),
    ("sacroiliite2", "Conclusão — sacroileíte inflamatória em atividade", "8148"),
    ("sacroiliite3", "Sinovite bilateral das sacroilíacas de natureza inflamatória", "8158"),
    ("sacroiliite4", "Edema subcondral no terço médio de ambos os ilíacos", "8166"),
    ("sacroiliite5", "Conclusão — sacroiliíte bilateral em atividade", "8172"),
    ("miositepelve1", "Edema muscular e perifascial — miopatia inflamatória", "8244"),
    ("coccix1", "Angulação anterior das últimas peças coccígeas", "7879"),
    ("coccix2", "Cóccix tipo IV de Postacchini com subluxação anterior", "8125", "bullet"),
    ("instabcoccix1", "Desalinhamento anterior da II peça coccígea com edema", "7894"),
    ("instabcoccix2", "Desalinhamento coccígeo com reação osteo-hipertrófica", "7897"),
    ("espiculacoccix1", "Pequena espícula óssea na última peça coccígea", "7891"),
    ("espiculacoccix2", "Conclusão — espícula óssea coccígea com realce adjacente", "8133", "bullet"),
    ("artrosacrococc1", "Alteração degenerativa sacrococcígea", "7888"),
    ("discoligamentar1", "Espessamento do complexo discoligamentar coccígeo", "7885"),
    ("sequelafxcoccix1", "TC — sequela de fratura da I peça coccígea", "9842"),
    ("cistomeningeo1", "Cisto meníngeo adjacente à raiz emergente de S1", "7884"),
    ("tarlov1", "Cisto perineural de Tarlov no nível sacral", "7900"),
    ("tarlov2", "Cistos perirradiculares de Tarlov nos forames sacrais", "6440"),
    ("lesaosacro1", "Lesão cística da massa lateral de S2 com remodelação foraminal", "6433"),
    ("lesaosacro2", "Comentário — formação cística sacral de provável origem neural", "6447"),

    ("#", "PLEXOS E DESFILADEIRO TORÁCICO"),

    ("raizesplexo1", "Raízes do plexo lombar e sacral com morfologia e sinal habitual", "6413"),
    ("trajetoneural1", "Trajetos neurais livres, sem sinais compressivos", "6414"),
    ("lesaoforaminal1", "Sem lesões compressivas foraminais ou pré-ganglionares", "6499"),
    ("fasciculos1", "Fascículos, troncos e nervos com gordura perineural preservada", "6500"),
    ("subclavia1", "Trajeto vascular subclávio e axilar preservado", "6501"),
    ("ventresplexo1", "Ventres musculares sem áreas de denervação", "6502"),
    ("costelacervical1", "Ausência de costelas cervicais", "6543"),
    ("compressaoespacos1", "Sem compressões nos espaços interescalênico e retropeitoral", "6668"),
    ("avulsaoraiz1", "Avulsão pré-ganglionar com pseudomeningocele", "6576"),
    ("avulsaoraiz2", "Avulsão pré-ganglionar de C6 a C8 com pseudomeningocele", "6610"),
    ("estiramentoraiz1", "Sinais de estiramento das raízes de C6 e C8", "6577"),
    ("obliteracaoplexo1", "Obliteração das estruturas do plexo no espaço interescalênico", "6578"),
    ("denervparaverteb1", "Edema da paravertebral por denervação muscular inicial", "6579"),
    ("mielopatiaplexo1", "Mielopatia pós-traumática por avulsão radicular", "6581"),
    ("plexoneoplasico1", "Espessamento e realce do plexo — infiltrativa x radioterápica", "6595"),
    ("fxclavicula1", "Fratura do terço médio da clavícula com desvio", "6608"),
    ("denervsupraesc1", "Edema do subescapular e supraespinhal por denervação aguda", "6612"),
    ("materialclavicula1", "Material metálico na clavícula com artefatos", "6575"),
    ("manobradesfil1", "Manobra dinâmica com compressão da subclávia", "6631", "bullet"),
    ("manobradesfil2", "Redução do calibre da veia subclávia após a manobra", "6662"),
    ("manobradesfil3", "ID — redução de 50% da veia axilar após a manobra", "6678"),

    ("#", "TRONCO: ESCÁPULA, PEITORAL, PAREDE ABDOMINAL E ARCOS COSTAIS"),

    ("escapulotorac1", "Relação escapulotorácica simétrica e preservada", "2711"),
    ("escapulotorac2", "Leve assimetria da relação escapulotorácica", "2712"),
    ("peitoralmaior1", "Rotura da junção miotendínea da cabeça costoesternal do peitoral", "6097", "bullet"),
    ("peitoralmaior2", "Conclusão — rotura de alto grau do peitoral maior", "6106", "bullet"),
    ("herniaumbilical1", "Hérnia umbilical com herniação de gordura peritonial", "5548"),
    ("diastasereto1", "Diástase dos músculos retoabdominais com afilamento da fáscia", "5551"),
    ("articintercondral1", "Articulação intercondral entre a 5ª e a 6ª cartilagens costais", "8346"),
    ("calccondrais1", "Calcificações periféricas nas cartilagens condrais", "8349"),
    ("xifoide1", "Apêndice xifoide com aspecto bífido", "8355"),
    ("sequelafxcostais1", "Sequelas de fraturas consolidadas em arcos costais", "12132", "bullet"),

    ("plexolombar1", "Raízes e troncos do plexo lombossacro sem alterações", "6438"),
    ("espondilodiscoart1", "Espondilodiscoartropatia degenerativa lombar (achado adicional)", "6442"),
    ("sacroiliacanl1", "Sem processos inflamatórios ou degenerativos nas sacroilíacas", "8074"),
    ("desfiladeirosupra1", "Redução da amplitude do desfiladeiro do supraespinal", "402"),
    ("piriformes1", "Ventres musculares dos piriformes simétricos", "6439"),
    ("ventresplexo3", "Ventres musculares preservados", "6441"),
    ("feixesplexo1", "Demais feixes neurovasculares com trajetos livres", "6443"),
    ("sinfisenl2", "Ausência de formações expansivas ou coleções na sínfise", "8270"),
    ("sinfisenl3", "Demais estruturas ósseas e planos miotendíneos preservados", "8269"),
    # ---- laudos completos ----
    ("rmsacroiliacas2", "RM das articulações sacroilíacas — edema subcondral inespecífico", "68-82"),
    ("rmsacroiliacas3", "RM das articulações sacroilíacas — normal", "7945-7987"),
    ("rmsacroiliacas4", "RM das sacroilíacas — irregularidade cortical com edema", "8189-8234"),
    ("rmsinfise", "RM da sínfise púbica — normal", "8285-8308"),
    ("rmsacro3", "RM da região sacrococcígea — normal", "7816-7857"),
    ("rmsacro4", "RM da região sacrococcígea — modelo com alterações", "7863-7928"),
    ("rmsacro5", "RM do sacrococcix — espícula óssea coccígea", "8119-8133"),
    ("rmplexo2", "RM do plexo lombar — normal", "6406-6423"),
    ("rmplexo3", "RM do plexo braquial bilateral — normal", "6489-6504"),
    ("rmplexo4", "RM do plexo braquial — espondilose cervical com capsulite", "6510-6564"),
    ("rmplexo5", "RM do plexo braquial — avulsão radicular com pseudomeningocele", "6571-6586"),
    ("rmplexo6", "RM do plexo braquial — trauma com fratura da clavícula", "6599-6619"),
    ("rmdesfiladeiro", "Angiorressonância do desfiladeiro torácico — modelo", "6624-6641"),
    ("rmdesfiladeiro2", "RM do plexo braquial — pesquisa de síndrome do desfiladeiro", "6649-6678"),
    ("rmescapula", "RM da escápula — normal", "2700-2731"),
    ("rmpeitoral", "RM do peitoral maior — rotura da cabeça costoesternal", "6090-6106"),
    ("rmparedeabd", "RM da parede abdominal — hérnia umbilical e diástase", "5533-5574"),
    ("tcarcoscostais", "TC de arcos costais — calcificações condrais", "8332-8370"),
    ("tccoccix", "TC de cóccix — sequela de fratura", "9839-9854"),
]
