# Coluna torácica e lombossacra
ENTRADAS = [
    ("#", "COLUNA TORÁCICA"),

    ("cifose1", "Acentuação da cifose torácica em decúbito", "2159"),
    ("cifoselordose1", "Acentuação da cifose torácica e da lordose lombar", "9600"),
    ("osteofitosdorsal1", "Esboços osteofitários marginais anteriores difusos", "2162"),
    ("costovertebral1", "Articulações interfacetárias e costovertebrais normais", "2165"),
    ("costovertebral2", "TC — articulações interfacetárias e costovertebrais íntegras", "9518"),
    ("costovertebral3", "TC — alterações degenerativas costovertebrais e costotransversas", "9616"),
    ("costocondral1", "TC — hipertrofia das articulações costocondrais", "9554"),
    ("hipohidratdorsal1", "Hipo-hidratação do disco intervertebral de T11-T12", "2168"),
    ("hipohidratdorsal2", "TC — hipo-hidratação discal difusa sem perda de altura", "9521"),
    ("modicdorsal1", "TC — irregularidade das placas terminais torácicas (Modic I/II)", "9515"),
    ("abauldorsal1", "T5-T6 — protrusão discal posterior mediana", "2171"),
    ("abauldorsal2", "T7-T8 — protrusão posterolateral à direita", "2174"),
    ("abauldorsal3", "T8-T9 — protrusão discal posterior mediana", "2177"),
    ("abauldorsal4", "T9-T10 — protrusão paramediana tocando a medula", "2180"),
    ("abauldorsal5", "T11-T12 — mínimo abaulamento discal posterior", "2183"),
    ("abauldorsaltc1", "TC — discreto abaulamento discal em T11-T12", "9524"),
    ("calcligamarelo1", "TC — calcificação do ligamento amarelo em D10", "9569"),
    ("artrointerfacdors1", "TC — artropatia degenerativa das interfacetárias torácicas", "9557"),
    ("escoliosetoraco1", "TC — postura escoliótica toracolombar", "9548"),
    ("espondilosedorsal1", "Discreta espondilose dorsal", "2207"),
    ("discopatiadorsal1", "Discopatia degenerativa de T11-T12 sem contatos neurais", "2210"),
    ("espondiloartrdors1", "Conclusão — espondiloartrose da coluna dorsal", "9580"),
    ("acunhamentod12", "Leve acunhamento anterior de D12, provavelmente constitucional", "261"),
    ("acunhamentot8", "Acunhamento anterior de T8 por insuficiência óssea", "9604"),
    ("fxt10", "Fratura de T10 com desalinhamento dos fragmentos", "9601-9603", "unir"),
    ("fxcronicas1", "Fraturas crônicas de T7 a L2 com esclerose", "374", "bullet"),
    ("fxtrauma1", "Fratura oblíqua de T8 com retropulsão do muro posterior", "2662"),
    ("roturaligamarelo1", "Rotura do ligamento amarelo com subluxação das interfacetárias", "2667"),
    ("colapsoplacas1", "Colapso das placas terminais superiores pós-traumático", "2675"),
    ("laminas1", "Irregularidade da cortical das lâminas de T8", "2678"),
    ("mielopatia1", "Alteração de sinal da medula torácica por mielopatia pós-traumática", "2681"),
    ("paravertebral1", "Alteração de sinal da musculatura e ligamentos paravertebrais", "2672"),
    ("artrodesetorac1", "Laminectomia com artrodese posterior de T4 a T7", "2446", "bullet"),
    ("artrodesetorac2", "Artrodese posterior de T7 a T10 com espaçador", "9488"),

    ("#", "COLUNA LOMBOSSACRA"),

    # ---- alinhamento, corpos vertebrais, transição ----
    ("corposlombnl1", "Corpos vertebrais com altura e alinhamento preservados", "816"),
    ("lordoseacent1", "Acentuação da lordose fisiológica na posição do exame", "381", "bullet"),
    ("lordoseacent2", "Acentuação da lordose lombar em decúbito", "2519"),
    ("lordoseacent3", "TC — acentuação da lordose em decúbito", "9678"),
    ("retificalomb1", "TC — retificação da lordose fisiológica em decúbito", "9679"),
    ("acentuacurvat1", "TC — acentuação das curvaturas torácica e lombar", "9680"),
    ("escoliose1", "Escoliose toracolombar com hemivértebra", "870"),
    ("escoliose2", "Retificação da lordose com escoliose lombar", "2414", "bullet"),
    ("escoliose3", "Conclusão — escoliose lombar para a esquerda", "2431"),
    ("escoliose4", "Acentuado desvio escoliótico da coluna lombar", "11473"),
    ("escoliose5", "TC — desvio toracolombar com componente rotacional", "9659"),
    ("laterolistese1", "Laterolistese de L2 e L3 à direita", "11481"),
    ("infradesnivel1", "Infradesnivelamento da crista ilíaca", "874"),
    ("retrolistese1", "Retrolistese degenerativa escalonada de L2, L3 e L4", "380"),
    ("retrolistese2", "Mínima retrolistese de L4 sobre L5 (grau I)", "887"),
    ("retrolistese3", "Discreta retrolistese de L3 sobre L4", "2415"),
    ("retrolistese4", "Conclusão — discreta retrolistese de L3", "2432"),
    ("retrolistese5", "Retrolistese de L1-L2 com anterolistese de L2-L3", "11479"),
    ("retrolistese6", "Discreta retrolistese degenerativa de L2", "11611", "bullet"),
    ("anterolistelomb1", "Anterolisteses grau I em L4-L5 e L5-S1", "206"),
    ("anterolistelomb2", "Anterolisteses degenerativas grau I em L4 e L5", "2294"),
    ("anterolistelomb3", "Anterolistese de L4 sobre L5 e L5 sobre S1 (grau I)", "2515"),
    ("anterolistelomb4", "Anterolistese degenerativa grau I de L3", "12239", "bullet"),
    ("anterolistelomb5", "TC — anterolistese degenerativa de L4-L5", "9660"),
    ("anterolistelomb6", "TC — anterolistese de L5-S1 com lise do istmo", "9661"),
    ("anterolistet1", "Anterolistese grau I de T1 sobre T2, degenerativa", "9605"),
    ("anterolistel5", "Anterolistese grau I de L5 sobre S1, degenerativa", "9606"),
    ("espondilolise1", "Lise crônica dos istmos de L5 com anterolistese", "379"),
    ("espondilolise2", "Espondilólise do istmo de L5 à direita", "2514"),
    ("vertrans1", "Vértebra de transição lombossacra com sacralização de L5", "500", "bullet"),
    ("vertrans2", "Vértebra de transição com lombarização de S1", "2405", "bullet"),
    ("vertrans3", "Sacralização de L5 com megapófise transversa", "2510"),
    ("vertrans4", "Vértebra de transição — recomendação de correlação radiográfica", "1593"),
    ("vertrans5", "Vértebra de transição com megapófise articulada ao sacro", "1598"),
    ("pediculocurto1", "Pedículos curtos com espessamento do ligamento amarelo", "514"),
    ("pediculocurto2", "Pedículos lombares de L3 a L5 de configuração curta", "515"),
    ("pediculocurto3", "Pedículos de morfologia constitucionalmente curta de L2 a L5", "891"),
    ("vertebralimbo1", "Irregularidade do bordo ântero-superior de L5 (vértebra em limbo)", "9670"),
    ("enostose1", "Enostose (ilhota óssea) no ilíaco direito", "9781"),

    # ---- platôs, discos e osteófitos ----
    ("osteofitosschmorl1", "Corpos vertebrais com osteófitos e herniações de Schmorl", "382", "bullet"),
    ("osteofitoslomb1", "Osteófitos marginais incipientes de L3 a L5", "890"),
    ("osteofitoslomb2", "TC — osteófitos marginais incipientes difusos", "9683"),
    ("osteofitoslomb3", "TC — osteófitos marginais proeminentes nos platôs", "9684"),
    ("osteofitosacent1", "Osteófitos marginais acentuados nos corpos vertebrais", "11485"),
    ("osteofitosepontes1", "Osteofitose marginal com pontes ósseas anterolaterais", "9608-9610", "unir"),
    ("schmorl1", "Nódulos de Schmorl nos planaltos vertebrais", "2298"),
    ("schmorl2", "Herniação intrassomática de Schmörl aguda ou crônica", "2533"),
    ("schmorl3", "Herniações discais intrassomáticas esparsas", "11613"),
    ("schmorl4", "TC — herniações de Schmorl em T12, L2, L3 e L5", "9693"),
    ("schmorl5", "TC — herniação de Schmorl com degeneração gasosa", "9696"),
    ("modiclomb1", "Irregularidades com edema (Modic I) nos platôs de L4-L5", "652"),
    ("modiclomb2", "Degeneração edematosa/gordurosa de L5-S1 (Modic I/II)", "817"),
    ("modiclomb3", "Alterações degenerativas discogênicas Modic I/II", "2297"),
    ("modiclomb4", "Edema e degeneração gordurosa (Modic I e II) em L3-L4 e L4-L5", "2418"),
    ("modiclomb5", "Focos de edema nas margens anteriores de L1 a L3", "2454"),
    ("modiclomb6", "Irregularidade e degeneração das placas terminais (Modic I/II)", "2536"),
    ("modiclomb7", "Degeneração edematosa/gordurosa de L2-L3 a L4-L5", "11489"),
    ("modiclomb8", "Alterações Modic I/II em L4-L5 e L5-S1", "12241", "bullet"),
    ("entesopatiamarg1", "Edema ósseo na margem ântero-superior por entesopatia", "818"),
    ("entesopatiamarg2", "Edema ósseo ântero-superior de L4 e L5 por entesopatia", "2465"),
    ("discopatiamulti1", "Discopatia degenerativa multissegmentar com focos gasosos", "383", "bullet"),
    ("discopatialomb1", "Discopatia de L2-L3 e L5-S1 com Modic II", "739"),
    ("discopatialomb2", "Conclusão — discopatia degenerativa de L5-S1", "830"),
    ("discopatialomb3", "Conclusão — discopatia multissegmentar com estenose", "2434"),
    ("discopatialomb4", "Discopatia degenerativa com hipo-hidratação de L4-L5 e L5-S1", "12299", "bullet"),
    ("hipohidratlomb1", "Hipo-hidratação discal de L3-L4 a L5-S1", "622", "bullet"),
    ("hipohidratlomb2", "Hipo-hidratação discal com redução da altura em L5-S1", "820"),
    ("hipohidratlomb3", "Hipo-hidratação com redução difusa da altura discal", "11491"),
    ("hipohidratlomb4", "Redução da hidratação discal de L3-L4 e L4-L5", "12612"),
    ("desidratlomb1", "Desidratação discal lombar difusa (máscara)", "2301"),
    ("desidratlomb2", "Desidratação discal difusa com redução em L3-L4", "2419"),
    ("desidratlomb4", "Máscara — hipo-hidratação dos discos em (nível a preencher)", "2552"),
    ("desidratlomb3", "Desidratação discal difusa com redução da altura", "2553"),
    ("reducaodiscal1", "Redução dos espaços discais com Schmorl e esclerose", "208"),
    ("reducaodiscal2", "TC — discreta redução do espaço discal de L5-S1", "9701"),
    ("reducaodiscal3", "TC — redução discal com esclerose e degeneração gasosa", "9702"),
    ("reducaodiscal4", "TC — redução difusa dos espaços discais", "9703"),
    ("hemangiomalomb1", "Hemangiomas ósseos ou depósito de gordura focal", "2299"),
    ("hemangiomalomb2", "Foco nodular de degeneração gordurosa e/ou hemangioma", "2526"),
    ("nodulot2", "Imagem nodular vertebral com baixo sinal em todas as sequências", "2529"),
    ("nodulot2b", "Imagem nodular vertebral inespecífica — controle evolutivo", "2653", "bullet"),
    ("hemangiomalomb3", "Foco nodular de L1 — hemangioma atípico, controle evolutivo", "469"),

    # ---- interfacetárias, ligamentos e Baastrup ----
    ("artrointerfaclomb1", "Artrose interfacetária multissegmentar", "390", "bullet"),
    ("artrointerfaclomb2", "Artropatia degenerativa interfacetária de L3-L4 a L5-S1", "819"),
    ("artrointerfaclomb3", "Artrose interfacetária mais acentuada em L4-L5 e L5-S1", "2311"),
    ("interfacetlomb1", "Artropatia interfacetária difusa com lâmina líquida", "2425", "bullet"),
    ("interfacetlomb2", "Alterações interfacetárias com líquido intra-articular", "2541"),
    ("interfacetlomb3", "Alterações interfacetárias com líquido à direita", "2542"),
    ("interfacetlomb4", "Alterações degenerativas moderadas das interfacetárias", "11487"),
    ("interfacetlomb5", "Derrame articular nas interfacetárias de L3-L4", "12616", "bullet"),
    ("interfacetlomb6", "TC — leves alterações das interfacetárias de L2-L3 e L3-L4", "9688"),
    ("interfacetlomb7", "TC — artropatia interfacetária com degeneração gasosa", "9689"),
    ("interfacetlomb8", "TC — hipertrofia das interfacetárias de L2-L3 a L5-S1", "9690"),
    ("interapofis1", "Artrose das interapofisárias com estenose relativa", "2413"),
    ("interapofis2", "Alterações degenerativas das interapofisárias torácicas e lombares", "9613-9615", "unir"),
    ("cistointerfacet1", "Cisto artrossinovial da interfacetária com contato radicular", "11619", "bullet"),
    ("ligamarelolomb1", "Espessamento dos ligamentos amarelos de L2 a L4", "893"),
    ("ligamarelolomb2", "Espessamento dos ligamentos amarelos de L2-L3 a L5-S1", "2545"),
    ("baastrup1", "Artrose interespinhosa (Baastrup) com edema por sobrecarga", "2417"),
    ("baastrup2", "Conclusão — artrose interespinhosa (Baastrup)", "2435"),
    ("baastrup3", "Sinais de Baastrup de L1-L2 a L4-L5", "2589"),
    ("baastrup4", "Sinais de Baastrup com hipertrofia dos processos espinhosos", "11504"),
    ("baastrup5", "TC — sinais de Baastrup em L3-L4 e L4-L5", "9757"),
    ("interespinhoso1", "Edema dos ligamentos interespinhais de L5-S1", "825"),
    ("interespinhoso2", "Edema dos ligamentos interespinhosos por sobrecarga mecânica", "2315"),
    ("interespinhoso3", "Conclusão — edema do espaço ligamentar interespinhoso", "2436"),
    ("interespinhoso4", "Leve edema dos ligamentos interespinhosos por sobrecarga", "11623"),
    ("interespinhoso5", "Edema do ligamento interespinhoso de L3-L4 a L5-S1", "12253"),

    # ---- discopatias por nível ----
    ("abaullomb1", "L1-L2 — pequeno abaulamento com impressão dural", "384", "bullet"),
    ("abaullomb2", "L2-L3 — disco-osteofitário com raízes emergentes de L2", "385", "bullet"),
    ("abaullomb3", "L3-L4 — disco-osteofitário assimétrico com estenose foraminal", "386", "bullet"),
    ("abaullomb4", "L4-L5 — disco-osteofitário com impressão dural", "387", "bullet"),
    ("abaullomb5", "L5-S1 — abaulamento com artrose interfacetária", "388", "bullet"),
    ("abaullomb6", "L3-L4 — leve abaulamento com espessamento dos ligamentos amarelos", "403"),
    ("abaullomb7", "L4-L5 — protruso mediano com redução do canal vertebral", "404"),
    ("abaullomb8", "L5-S1 — fissura do ânulo com protrusão foraminal direita", "405"),
    ("abaullomb9", "L4-L5 — protrusão discal foraminal direita", "413", "bullet"),
    ("abaullomb10", "L5-S1 — abaulamento simétrico com raízes descendentes de S1", "414", "bullet"),
    ("abaullomb11", "L5-S1 — protrusão centrolateral esquerda com contato radicular", "493"),
    ("abaullomb12", "L3-L4 e L4-L5 — abaulamento sem contatos neurais", "623", "bullet"),
    ("abaullomb13", "L5-S1 — extrusão póstero-central com migração caudal", "624", "bullet"),
    ("abaullomb14", "L4-L5 — extrusão migrada com compressão radicular", "650", "bullet"),
    ("abaullomb15", "L5-S1 — fissura do ânulo com leve abaulamento", "651", "bullet"),
    ("abaullomb16", "L5-S1 — abaulamento assimétrico com contato radicular", "821"),
    ("abaullomb17", "L2-L3 — protruso póstero-central sem repercussões", "895"),
    ("abaullomb18", "L3-L4 — extruso com migração e estenose do canal", "896"),
    ("abaullomb19", "L4-L5 — protruso com rotura de fibras do anel fibroso", "897"),
    ("abaullomb20", "L3-L4 — abaulamento com insinuação biforaminal", "947", "bullet"),
    ("abaullomb21", "Abaulamento com artrose interfacetária e redução foraminal", "1018"),
    ("abaullomb22", "Abaulamento assimétrico com maior componente foraminal", "2410"),
    ("abaullomb23", "L1-L2 — abaulamento difuso sem conflitos radiculares", "2420"),
    ("abaullomb24", "L2-L3 — abaulamento com hipertrofia das facetas", "2421"),
    ("abaullomb25", "L3-L4 — assimétrico foraminal direito com contato radicular", "2422"),
    ("abaullomb26", "L4-L5 — abaulamento com redução dos recessos laterais", "2423"),
    ("abaullomb27", "L5-S1 — assimétrico foraminal esquerdo com contato radicular", "2424"),
    ("abaullomb28", "L2-L3 — extrusão centrolateral esquerda com estenose", "2457"),
    ("abaullomb29", "L3-L4 — mínimo abaulamento posterior", "2472"),
    ("abaullomb30", "L4-L5 — abaulamento simétrico com obliteração foraminal", "2473"),
    ("abaullomb31", "L5-S1 — redução da altura com Modic II e fusão óssea", "2474"),
    ("abaullomb32", "L2-L3 — pequeno abaulamento com redução foraminal", "2561"),
    ("abaullomb33", "L3-L4 — abaulamento com contato radicular foraminal", "2562"),
    ("abaullomb34", "L4-L5 — disco-osteofitário com anterolistese e estenose", "2563"),
    ("abaullomb35", "L5-S1 — disco-osteofitário com anterolistese", "2564"),
    ("abaullomb36", "D12-L1 a L2-L3 — abaulamentos com redução foraminal", "11493"),
    ("abaullomb37", "L3-L4 — abaulamento com moderada estenose do canal", "11495"),
    ("abaullomb38", "L4-L5 — abaulamento com contato radicular à direita", "11497"),
    ("abaullomb39", "L5-S1 — abaulamento difuso sem contato radicular", "11499"),
    ("abaullomb40", "L2-L3 — abaulamento com insinuação foraminal bilateral", "11615", "bullet"),
    ("abaullomb41", "L1-L2 — protruso paramediano direito com compressão dural", "12245", "bullet"),
    ("abaullomb42", "L2-L3 — disco-osteofitário com redução foraminal", "12246", "bullet"),
    ("abaullomb43", "L3-L4 — protruso mediano com moderada estenose de canal", "12247", "bullet"),
    ("abaullomb44", "L4-L5 — assimétrico à esquerda com contato radicular", "12248", "bullet"),
    ("abaullomb45", "L5-S1 — protruso mediano com contato radicular", "12249", "bullet"),
    ("abaullomb46", "L4-L5 — abaulamento com fissura do ânulo foraminal", "12300", "bullet"),
    ("abaullomb47", "L5-S1 — pequeno abaulamento sem conflitos radiculares", "12301", "bullet"),
    ("abaullomb48", "L3-L4 — abaulamento com fissuras do ânulo fibroso", "12613"),
    ("abaullomb49", "L4-L5 — manipulação cirúrgica do contorno discal com espaçador", "12614"),
    ("abaullomb50", "L5-S1 — pequeno abaulamento com insinuação foraminal", "12615"),
    ("abaullombmask1", "Máscara — abaulamento comprimindo o saco dural e os forames", "2307"),
    ("abaullombmask2", "Máscara — abaulamento comprimindo o saco dural", "2308"),
    ("abaullombmask3", "Máscara — abaulamento com estenose do canal vertebral", "2309"),
    ("abaullombtc1", "TC — abaulamento comprimindo o saco dural e os forames", "218"),
    ("abaullombtc2", "TC — abaulamento com contato radicular emergente", "219"),
    ("abaullombtc3", "TC — abaulamento com contato das raízes emergentes", "220"),
    ("abaullombtc4", "TC — L3-L4 com estenose foraminal osteofitária", "9708"),
    ("abaullombtc5", "TC — L2-L3 assimétrico foraminal esquerdo", "9709"),
    ("abaullombtc6", "TC — L3-L4 e L4-L5 pequenos abaulamentos posteriores", "9712"),
    ("abaullombtc7", "TC — L5-S1 com componente protruso póstero-central", "9715"),
    ("abaullombtc8", "TC — L3-L4 mínimo abaulamento posterior", "9718"),
    ("abaullombtc9", "TC — L4-L5 protruso póstero-lateral direito", "9721"),
    ("abaullombtc10", "TC — L5-S1 com anterolistese e compressão radicular", "9724"),
    ("abaullombtc11", "TC — L3-L4 com redução foraminal à esquerda", "9725"),
    ("abaullombtc12", "TC — L4-L5 com estenose foraminal bilateral", "9729"),
    ("abaullombtc13", "TC — L4-L5 disco-osteofitário póstero-lateral direito", "9732"),
    ("abaullombtc14", "TC — L5-S1 pequeno abaulamento com componente protruso", "9738"),
    ("estenoselomb1", "Estenose do canal de L3-L4 a L5-S1 com agrupamento da cauda equina", "516"),
    ("estenoselomb2", "Estenose do canal de L2-L3 a L4-L5", "2426", "bullet"),
    ("lipomatoseep1", "Lipomatose epidural com agrupamento das raízes da cauda equina", "2471"),
    ("sequestrodiscal1", "Imagem extradural foraminal — sequestro discal", "2507", "bullet"),
    ("canalamplo1", "Canal vertebral amplo", "822"),
    ("conemedular1", "Cone medular de contornos regulares e sinal homogêneo", "823"),

    # ---- musculatura paravertebral ----
    ("lipossubstparav1", "Lipossubstituição da musculatura paravertebral posterior", "901"),
    ("lipossubstparav2", "Lipossubstituição/hipotrofia da paravertebral de L3 a S2", "2585"),
    ("hipotrofiaparav1", "Moderada hipotrofia e lipossubstituição da paravertebral", "11503"),
    ("estriasgordurosas1", "Estrias gordurosas na musculatura paravertebral posterior", "2428", "bullet"),
    ("atrofiaparavert1", "Atrofia e lipossubstituição da paravertebral pós-cirúrgica", "2487"),

    # ---- pós-operatório ----
    ("artrodeselomb1", "Artrodese posterior com laminectomia e tecido fibrocicatricial", "886"),
    ("artrodeselomb2", "Artrodese posterior com parafusos transpediculares e cage", "193"),
    ("artrodeselomb3", "Artrodese de L2-L4 com laminectomia", "11707"),
    ("artrodeselomb4", "TC — artrodese de L4 a S1 com alterações fibrocicatriciais", "9641"),
    ("artrodeselomb5", "TC — artrodese de L3 a S1 com laminectomia ampla", "9646"),
    ("artrodeselomb6", "TC — artrodese com parafusos e hastes posteriores", "9491"),
    ("soltura1", "TC — halo hipodenso ao redor dos parafusos, compatível com soltura", "9642"),
    ("poscirurglomb1", "Máscara — laminectomia com cage e artrodese", "2288"),
    ("poscirurglomb2", "Máscara — tecido fibrocicatricial epidural pós-operatório", "2289"),
    ("poscirurglomb3", "Máscara — coleção com realce periférico pós-operatória", "2290"),
    ("poscirurglomb4", "Laminectomia e facetectomia com espaçador intersomático", "2480"),
    ("poscirurglomb5", "Laminectomia e facetectomia com discectomia em L5-S1", "2485"),
    ("poscirurglomb6", "Tecido fibrocicatricial com realce e diminuta coleção", "2486"),
    ("poscirurglomb7", "Laminectomia esquerda de L4-L5", "2493", "bullet"),
    ("poscirurglomb8", "Artrodese posterior de L5 com laminectomia ampla de L4", "12592", "bullet"),
    ("poscirurglomb9", "Controle de laminectomia ampla em L4-L5", "2003"),
    ("poscirurglomb10", "Controle pós-operatório de fusão lombar anterior", "630"),
    ("fibroseepidural1", "Tecido fibrocicatricial epidural envolvendo a raiz L4", "2492"),
    ("colecaoposop1", "Acúmulo líquido na topografia dos arcos posteriores ressecados", "11708"),
    ("ressecaolesao1", "Ressecção de lesão expansiva intramedular", "11710"),
    ("siringomielia1", "Redução da hidrossiringomielia do filo terminal", "11711"),
    ("dropmetastasis1", "Realce nodular suspeito para disseminação liquórica", "11713"),
    ("aracnoidite1", "Espessamento e realce dural — aracnoidite pós-operatória", "11715"),
    ("neuropatiapos1", "Realce da raiz S1 por neuropatia pós-cirúrgica", "11716"),
    ("materialcirurg1", "TC — focos de alta densidade no canal vertebral", "9743"),

    # ---- fraturas, lesões secundárias e infecção ----
    ("fxagudal1", "Fratura aguda do corpo vertebral de L1", "11475"),
    ("impactacoestrab1", "Impactações trabeculares de D11 a L5", "11477"),
    ("fxcolapso1", "TC — fratura/colapso de D11 com 60% de redução", "9665"),
    ("fxplatosuperior1", "TC — fratura do platô superior de L3", "9666"),
    ("fxcolapso2", "TC — fratura/colapso de L4 com 50% de redução", "9667"),
    ("fxcompressival1", "Fratura compressiva do platô superior de L1", "12078"),
    ("fxpatologica1", "Fratura patológica de D1 com retropulsão e compressão medular", "2629"),
    ("metastasecoluna1", "Múltiplas lesões vertebrais de natureza secundária", "2614"),
    ("metastasecoluna2", "Infiltração da medular de T9 com extensão aos pedículos", "2615"),
    ("metastasecoluna3", "Infiltração de L2 com rotura da cortical — lesão secundária x linfoma", "2618"),
    ("metastasecoluna4", "TC — heterogeneidade da medular com áreas líticas", "2625"),
    ("metastasebacia1", "Múltiplas lesões ósseas secundárias nos ossos da bacia", "2621"),
    ("espondilodiscite1", "Espondilodiscite de T6-T7", "2635"),
    ("espondilodiscite2", "Espondilodiscite cervical extensa com coleções", "2639"),
    ("reconvmed4", "Sinal heterogêneo da medular óssea — reconversão medular", "2501", "bullet"),
    ("reconvmed5", "Aspecto heterogêneo da medular óssea vertebral", "2504", "bullet"),
    ("medulavermelha1", "Preservação da medula vermelha nos corpos vertebrais cervicais", "2657"),
    ("lesoesagressivas1", "Lesões ósseas agressivas ausentes", "377", "bullet"),
    ("obsrm1", "Obs. — sugestão de correlação com ressonância magnética", "9583"),
    ("obsrm2", "Obs. — sugestão de correlação com tomografia computadorizada", "2682"),

    ("abaullomb51", "L2-L3 e L3-L4 — abaulamento simétrico com insinuação biforaminal", "137", "bullet"),
    ("abaullomb52", "L4-L5 — assimétrico com fissura concêntrica do ânulo", "138", "bullet"),
    ("modiclomb9", "Alteração Modic I e II nos platôs de L5-S1", "264"),
    ("corposdorsolomb1", "Demais corpos vertebrais com alinhamento e alturas preservados", "9607"),
    ("discosnl1", "Demais discos intervertebrais sem protrusões significativas", "389", "bullet"),
    ("canalforamesnl1", "Canal vertebral e forames neurais de amplitude normal", "391", "bullet"),
    ("liticasnl1", "TC — não são observadas lesões líticas ou blásticas", "9612"),
    ("estudolombar1", "Realizado estudo da coluna lombar de L3 a S1", "9619"),
    ("espondiloselomb3", "Sinais de espondilose lombar", "2399"),
    # ---- laudos completos ----
    ("rmdorsal", "RM de coluna dorsal — modelo mestre com alternativas", "2108-2135"),
    ("rmdorsal2", "RM de coluna dorsal — espondilose com discopatias", "2145-2210"),
    ("rmlombar2", "RM de coluna lombar — espondilose com discopatia de L5-S1", "815-830"),
    ("rmlombar3", "RM de coluna lombar — escoliose com hemivértebra", "868-875"),
    ("rmlombar4", "RM de coluna lombar — pós-artrodese com estenose", "883-901"),
    ("rmlombar5", "RM de coluna lombar — admissional, normal", "2216-2268"),
    ("rmlombar6", "RM de coluna lombar — modelo mestre com máscaras", "2282-2319"),
    ("rmlombar7", "RM de coluna lombossacra — modelo mestre com alternativas e lacunas a preencher", "2325-2396"),
    ("rmlombar8", "RM de coluna lombar — modelo com estenose e Baastrup", "2405-2436"),
    ("rmlombar9", "RM de coluna lombar — escoliose com fraturas por insuficiência", "11466-11512"),
    ("rmlombar10", "RM de coluna lombar — pós-ressecção de lesão intramedular", "11701-11729"),
    ("rmlombar11", "RM de coluna lombar — espondilodiscoartropatia degenerativa", "12230-12253"),
    ("rmlombar12", "RM de coluna lombar — artrodese de L4-L5 com espaçador", "12599-12624"),
    ("rmlombar13", "RM de coluna lombar — abaulamentos com cisto interfacetário", "11606-11631"),
    ("tclombar", "TC de coluna lombossacra — artrodese posterior", "196-224"),
    ("tclombar2", "TC de coluna lombar — modelo mestre com alternativas", "9631-9781 !9653,9662"),
    ("tcdorsal", "TC de coluna dorsal — espondilose", "9495-9536"),
    ("tcdorsal2", "TC de coluna dorsal — espondiloartrose sem lesões secundárias", "9539-9583"),
    ("tcdorsal3", "TC de coluna dorsal — controle de artrodese de D5 a D9", "12180-12196"),
]
