# Tornozelo e pé
ENTRADAS = [
    ("#", "TORNOZELO / PÉ"),

    # ---- ligamentos laterais ----
    ("talofib1", "Afilamento fibrocicatricial do talofibular anterior e calcaneofibular", "8450"),
    ("talofib2", "Rotura completa do fibulotalar anterior com sequela de avulsão", "8648"),
    ("talofib3", "Rotura parcial extensa do fibulotalar anterior e fibulocalcâneo", "8649"),
    ("talofib4", "Edema por tração/avulsão no tálus e maléolo lateral", "8652", "bullet"),
    ("talofib5", "Rotura extensa do talofibular anterior e calcaneofibular, aguda", "8653"),
    ("talofib6", "Rotura completa do talofibular anterior e calcaneofibular", "8654"),
    ("talofib7", "Rotura parcial do talofibular anterior e calcaneofibular", "8655"),
    ("talofib8", "Estiramento do ligamento talofibular anterior", "8656"),
    ("talofib9", "Afilamento cicatricial do talofibular anterior e calcaneofibular", "8661"),
    ("talofib10", "Espessamento crônico cicatricial do talofibular anterior", "8662"),
    ("talofib11", "Espessamento cicatricial — sequela de rotura parcial pregressa", "8663"),
    ("talofib12", "Afilamento cicatricial com cistos artrossinoviais de permeio", "8664"),
    ("talofib13", "Lesão parcial de alto grau do talofibular anterior e calcaneofibular", "8825", "bullet"),
    ("talofib14", "Espessamento do talofibular anterior inferindo lesão prévia", "8857"),
    ("talofib15", "Edema dos planos circunjacentes ao talofibular anterior", "8886"),
    ("talofib16", "Ligamento calcaneofibular íntegro com edema periligamentar", "843"),
    ("talofibpost1", "Edema e cistos no maléolo lateral junto ao talofibular posterior", "8608"),
    ("sindesmose1", "Lesão parcial do tibiofibular anterior inferior", "8826", "bullet"),
    ("tibiofibant1", "Espessamento fibrocicatricial do tibiofibular anterior", "6013"),

    # ---- complexo deltoide e medial ----
    ("ligdeltoide2", "Estiramento com rotura parcial das fibras profundas do deltoide", "8449"),
    ("ligdeltoide3", "Estiramento dos folhetos profundos do ligamento deltoide", "8668"),
    ("ligdeltoide4", "Rotura parcial das fibras posteriores e profundas do deltoide", "8669"),
    ("ligdeltoide5", "Rotura parcial dos componentes profundos do deltoide", "8670"),
    ("ligdeltoide6", "Rotura extensa dos componentes superficial e profundo do deltoide", "8671"),
    ("ligdeltoide7", "Sequela de rotura do folheto superficial com fragmento avulsivo", "8672"),
    ("ligdeltoide8", "Espessamento crônico dos folhetos do ligamento deltoide", "8673"),
    ("ligdeltoide9", "Alteração fibrocicatricial do deltoide com desinserção parcial", "8674"),
    ("ligdeltoide10", "Alterações cicatriciais do deltoide nas fibras profundas", "8675"),
    ("ligdeltoide11", "Lesão parcial dos componentes profundo e superficial do deltoide", "8827", "bullet"),
    ("ligdeltoide12", "Edema circunjacente ao deltoide com alterações fibrocicatriciais", "8884"),
    ("ligdeltoide13", "Rotura extensa do complexo ligamentar deltoide", "12266", "bullet"),
    ("ligdeltoide14", "Edema circunjacente ao deltoide com rotura dos folhetos profundos", "844"),
    ("spring1", "Má delimitação do complexo ligamentar Spring", "8582"),
    ("spring2", "Espessamento do ligamento calcaneonavicular (Spring)", "8858"),
    ("spring3", "Edema dos planos circunjacentes ao ligamento Spring", "8885"),
    ("ligbifurcado1", "Rotura parcial do ligamento bifurcado", "12328"),
    ("retinaculoflex1", "Rotura focal do retináculo dos flexores", "12269", "bullet"),

    # ---- tendões fibulares ----
    ("fibulares1", "Tenossinovite dos fibulares com distensão da bainha comum", "8453"),
    ("fibulares2", "Tendinopatia e tenossinovite dos fibulares perimaleolar", "8684"),
    ("fibulares3", "Tendinopatia e tenossinovite do fibular longo", "8685"),
    ("fibulares4", "Lâmina de líquido na bainha comum dos fibulares", "8686"),
    ("fibulares5", "Tenossinovite dos fibulares retro e inframaleolar", "8687"),
    ("fibulares6", "Rotura tipo split do fibular curto na deflexão maleolar", "8688"),
    ("fibulares7", "Tenossinovite acentuada com fissura longitudinal do fibular curto", "8689"),
    ("fibulares8", "Tendinopatia do fibular curto com roturas longitudinais", "8865"),
    ("fibulares9", "Leve tendinopatia dos fibulares com quarto fibular", "12454", "bullet"),
    ("fibulares10", "Tenossinovite com tendinopatia do fibular curto inframaleolar", "851"),
    ("fibularquarto1", "Presença do fibular quarto", "8690"),
    ("fibularterceiro1", "Ventre muscular acessório (fibular terceiro)", "8866"),
    ("tuberculofib1", "Tubérculo dos fibulares proeminente com edema medular", "8693"),

    # ---- tibial posterior e flexores ----
    ("tibialpost1", "Leve tendinopatia insercional do tibial posterior", "8454"),
    ("tibialpost2", "Tenossinovite distal do tibial posterior", "8702"),
    ("tibialpost3", "Tendinopatia insercional do tibial posterior", "8703"),
    ("tibialpost4", "Tendinopatia inframaleolar do tibial posterior com ruptura parcial", "8704"),
    ("tibialpost5", "Fissura longitudinal do tibial posterior na inserção navicular", "8705"),
    ("tibialpost6", "Fissura intratendínea do tibial posterior retromaleolar", "8706"),
    ("tibialpost7", "Tendinopatia e tenossinovite justamaleolar do tibial posterior", "8709"),
    ("tibialpost8", "Roturas intrassubstanciais extensas do tibial posterior", "8864"),
    ("tibialpost9", "Rotura parcial do tibial posterior próxima à inserção navicular", "8889"),
    ("tibialpost10", "Leve tendinopatia insercional do tibial posterior com lâmina líquida", "12452", "bullet"),
    ("flexorhalux1", "Tenossinovite do flexor longo do hálux retromaleolar", "8717"),
    ("baxter1", "Neuropatia de Baxter — atrofia do abdutor do V dedo", "8720"),
    ("baxter2", "Atrofia do abdutor do hálux por denervação", "8847", "bullet"),
    ("cistoplantar1", "Formação cística junto ao trajeto do nervo plantar medial", "8846", "bullet"),

    # ---- tendão calcâneo e fáscia plantar ----
    ("tendaquiles1", "Tendinopatia do calcâneo com bursite retrocalcaneana", "6010"),
    ("tendaquiles2", "Leve tendinopatia do tendão calcâneo", "8456"),
    ("tendaquiles3", "Tendinopatia do calcâneo distal com entesófitos", "8752"),
    ("tendaquiles4", "Tendinopatia e peritendinite do calcâneo com fissura", "8753"),
    ("tendaquiles5", "Rotura completa justainsercional do tendão calcâneo", "8754"),
    ("tendaquiles6", "Rotura completa do tendão calcâneo com GAP", "8757"),
    ("tendaquiles7", "Discreta tendinopatia insercional do calcâneo", "12455", "bullet"),
    ("tendaquiles8", "TC — espessamento do tendão calcâneo por tendinopatia", "10659"),
    ("haglund1", "Tríade de Haglund", "8762"),
    ("entesofitocalc1", "Entesófito calcâneo plantar e posterior", "8729"),
    ("entesofitocalc2", "TC — proeminentes entesófitos plantar e posterior no calcâneo", "10656"),
    ("fasciiteplant1", "Fasciíte plantar justainsercional com entesite do calcâneo", "6009"),
    ("fasciiteplant2", "Fasciíte plantar com espessamento fusiforme e entesófito", "8455"),
    ("fasciiteplant3", "Fasciíte plantar com espessamento da banda central", "8730"),
    ("fasciiteplant4", "Fasciíte plantar com rotura transfixante da fáscia", "8731"),
    ("fasciiteplant5", "Espessamento crônico da banda central sem inflamação", "8732"),
    ("fasciiteplant6", "Espessamento da aponeurose plantar com entesófito", "8867"),
    ("fasciiteplant7", "Fasciíte plantar com entesófito calcaneano", "8888"),
    ("fasciiteplant8", "Leve fasciíte plantar com esporão plantar", "12457", "bullet"),
    ("fasciiteplant9", "Fasciíte plantar com espessamento do terço proximal", "853"),
    ("fasciaplantnl1", "Fáscia plantar íntegra com leve edema junto à origem", "8735"),
    ("gruberi1", "Líquido na bolsa de Gruberi", "8766"),

    # ---- osso e cartilagem do retropé/mediopé ----
    ("lesaoosteocond1", "Lesão osteocondral do domus talar com artropatia tibiotalar", "8546"),
    ("lesaoosteocond2", "Lesão osteocondral do domus talar com fragmento destacado", "8602"),
    ("condrotibiotalar1", "Leve afilamento condral tibiotalar com cistos subcondrais", "8556"),
    ("artrotibiotalar1", "Artropatia degenerativa tibiotalar com exposição óssea", "8557"),
    ("fxsubcondtalar1", "Fratura subcondral do domus talar", "8558"),
    ("condrosubtalar1", "Afilamento condral profundo da subtalar anterior", "8560"),
    ("condrosubtalar2", "Afilamento condral da subtalar média e anterior", "8580"),
    ("edemasubtalar1", "Edema e cistos subcondrais na subtalar posterior", "8561"),
    ("derramesubtalar1", "Derrame articular subtalar posterior", "8861"),
    ("corpolivresubtal1", "Corpo livre condral no recesso posterior", "8891"),
    ("artrocalcaneocub1", "Artropatia calcaneocuboide com subluxação medial do cuboide", "8579"),
    ("artrocalcaneocub2", "Alteração degenerativa calcaneocuboide", "8883"),
    ("artrotarsomet1", "Afilamento condral nas tarsometatarsais do IV e V raios", "5683"),
    ("artrotarsomet2", "Alterações degenerativas das articulações tarsometatarsais", "8559"),
    ("artrotarsomet3", "Afilamento condral nas tarsometatársicas do I e II raios", "8892"),
    ("condronavicul1", "Condropatia naviculocuneiforme com cistos subcondrais", "8448"),
    ("talonavicular1", "Espessamento capsuloligamentar talonavicular dorsal", "6018"),
    ("talonavicular2", "Leve espessamento capsuloligamentar talonavicular dorsal", "8511"),
    ("talonavicular3", "Reação osteo-hipertrófica talonavicular dorsal", "8543"),
    ("talonavicular4", "Rotura capsuloligamentar da talonavicular dorsal", "8820"),
    ("talonavicular5", "Desinserção capsuloligamentar talonavicular com avulsão", "8822"),
    ("talonavicular6", "Esclerose e reação osteo-hipertrófica talonavicular", "8868"),
    ("talonavicular7", "Rotura parcial capsuloligamentar talonavicular com contusão", "12327"),
    ("calcaneocub1", "Estiramento capsuloligamentar da calcaneocuboide", "12329"),
    ("avulsaocalccub1", "Rotura do calcaneocuboideo dorsolateral com avulsão óssea", "8818"),
    ("avulsaocronica1", "Avulsão óssea crônica junto à inserção distal", "8819"),
    ("ossifcalccub1", "Fragmento ósseo na calcâneo-cuboide — sequela x ossificação", "8821"),
    ("esclerosenavic1", "Esclerose subcondral do navicular por sobrecarga", "6019"),
    ("naviculocuneif1", "Espessamento capsuloligamentar naviculocuneiforme", "6020"),
    ("osteofitostalonav1", "Osteófitos talonaviculares, naviculocuneiformes e tarsometatársicos", "8540"),
    ("osteofitostibtal1", "Osteófitos e esclerose na tíbia distal e dorso do tálus", "6017"),
    ("osteofitosnavic1", "TC — reação osteo-hipertrófica na margem dorsal do navicular", "10651"),
    ("mullerweiss1", "Síndrome de Muller-Weiss", "8577"),
    ("mullerweiss2", "Síndrome de Muller-Weiss com subluxação e artrose secundária", "8578"),
    ("contusaomaleolo1", "Edema pós-contusional do maléolo medial e do domus talar", "8567"),
    ("contusaotalo1", "Edema pós-contusional do muro medial do domus talar", "846"),
    ("edemadomus1", "Edema subcondral no ângulo lateral do domus talar", "847"),
    ("edemadomus2", "Edema do muro lateral do domus talar", "8573"),
    ("edemadomus3", "Edema da face plantar da cabeça do tálus", "848"),
    ("edemametatibia1", "Edema da metáfise distal da tíbia por sobrecarga", "8570"),
    ("derrametibiotal1", "Mínimo derrame articular tibiotalar", "8452"),
    ("derrametibiotal2", "Pequeno derrame tibiotalar e subtalar com sinovite", "850"),
    ("remodelfibula1", "Remodelação da fíbula distal por manipulação cirúrgica", "8605"),
    ("avulsaomaleolat1", "Fratura/avulsão da extremidade distal do maléolo lateral", "842"),
    ("avulsaomaleomed1", "Fratura avulsiva do colículo anterior do maléolo medial", "12262", "bullet"),
    ("fxtibiadistal1", "TC — fratura completa oblíqua da metadiáfise distal da tíbia", "8840", "bullet"),
    ("fxmaleolopost1", "TC — fratura do maléolo posterior da tíbia", "8841", "bullet"),
    ("fxfibuladistal1", "TC — fratura cominutiva da diáfise distal da fíbula", "8842", "bullet"),
    ("seiotarso1", "Estiramento dos ligamentos interósseo e cervical do seio do tarso", "8869"),
    ("seiotarso2", "Gordura do seio do tarso preservada", "854"),
    ("cistotornozelo1", "Cisto artrossinovial cuneonavicular dorsal", "8791"),

    # ---- variantes e coalizões ----
    ("trigono1", "Osso trígono com edema junto à sincondrose", "8517"),
    ("trigono2", "Osso trígono com leve edema da medular óssea", "8534"),
    ("impactopost1", "Síndrome do impacto posterior com os trigonum", "8629"),
    ("impactosubfib1", "Impacto subfibular com valgismo do retropé", "8635"),
    ("impactosubfib2", "Pé plano com impacto subfibular e talocalcâneo", "8882"),
    ("impactosubtalar1", "Impacto subtalar do processo lateral do tálus", "8609"),
    ("navicacess1", "Presença de osso navicular acessório", "5614"),
    ("navicacess2", "Osso navicular acessório tipo I com tendinopatia do tibial posterior", "6011"),
    ("navicacess3", "Ossículo navicular acessório tipo III", "8537"),
    ("navicacess4", "Navicular acessório com instabilidade e tenossinovite", "8564"),
    ("navicacess5", "Osso navicular acessório com tênue edema na sincondrose", "8598"),
    ("navicacess6", "TC — osso navicular acessório bipartido", "10652"),
    ("osperoneum1", "Presença de os peroneum no tendão fibular longo", "8599"),
    ("fibularacess1", "TC — osso fibular acessório", "10653"),
    ("ossifcalcaneo1", "TC — ossificação junto à apófise anterior do calcâneo", "10654"),
    ("facetaacess1", "Faceta talar anterolateral acessória com edema subcondral", "8743"),
    ("processopostal1", "Hipertrofia do processo posterior do tálus", "6022"),
    ("coalizao1", "Coalizão fibrocartilaginosa talocalcaneana medial", "8617"),
    ("coalizao2", "Coalizão talocalcaneana medial com extensão à subtalar posterior", "8618"),
    ("coalizao3", "Coalizão fibrocartilaginosa calcaneonavicular", "8619"),
    ("coalizao4", "Coalizão talocalcaneana da subtalar medial posterior", "8620"),
    ("barracalcaneo1", "Barra não-óssea calcâneo-navicular", "865"),
    ("cuneiforme1", "Cuneiforme medial bipartido", "5794"),
    ("polidactilia1", "Polidactilia pós-axial com duplicação falângica", "5804", "bullet"),
    ("pecavo1", "Sinais de pé cavo e retropé varo", "6016"),
    ("pecavo2", "Pé aparentemente cavo — avaliar por radiografia com carga", "856"),
    ("peplano1", "Pé plano com retificação do arco plantar", "5892"),
    ("peplano2", "Sinais de pé plano — avaliar por radiografia com carga", "8447"),
    ("peplano3", "Pé plano e retropé valgo", "8522"),
    ("peplano4", "Pé plano com edema ósseo mecânico e derrame", "8849", "bullet"),

    # ---- antepé: hálux, sesamoides, metatarsos ----
    ("haluxvalgo1", "Discreto hálux valgo", "5611"),
    ("haluxvalgo2", "Valgismo metatarsofalângico do hálux com espessamento capsular", "5663"),
    ("haluxvalgo3", "Hálux valgo com luxação lateral dos sesamoides", "6035"),
    ("haluxvalgo4", "Hálux valgo com espessamento capsuloligamentar medial", "8873"),
    ("sesamoide1", "Sesamoide medial do hálux bipartido, sem alteração", "5602"),
    ("sesamoide2", "Sesamoide medial bipartido com edema medular mecânico", "5667"),
    ("sesamoide3", "Sesamoide lateral esclerótico — sesamoidite x osteonecrose", "5670"),
    ("sesamoide4", "Sesamoide medial bipartido com edema difuso", "5675"),
    ("sesamoide5", "Sesamoide medial bipartido com sesamoidite", "468", "bullet"),
    ("artrohalux1", "Artropatia da metatarsofalângica e glenossesamoides do hálux", "5676"),
    ("artrohalux2", "Artropatia do compartimento glenossesamoide medial", "5677"),
    ("glenossesam1", "Afilamento condral e esclerose do complexo glenossesamoideo", "8874"),
    ("derramemtf1", "Pequeno derrame na metatarsofalângica do II dedo", "5686"),
    ("sinovitemtf1", "Espessamento e realce sinovial nas metatarsofalângicas", "6040"),
    ("inflamatoriamtf1", "Derrame com sinovite nas metatarsofalângicas III a V", "5947"),
    ("artromtf1", "Artropatia com subluxação dorsal da falange do II raio", "5887"),
    ("luxdorsal1", "Luxação dorsal da falange proximal do II dedo", "6049"),
    ("dedosgarra1", "Deformidade em flexão das interfalângicas (dedos em garra)", "6038"),
    ("placaplantar1", "Rotura da placa plantar da II metatarsofalângica", "5719"),
    ("placaplantar2", "Degeneração das placas plantares com indefinição da IV", "6039"),
    ("placaplantar3", "Degeneração da placa plantar da I metatarsofalângica", "8875"),
    ("cistoplacaplant1", "Formação cística junto à placa plantar do IV dedo", "5723"),
    ("cistomtf1", "Formação cística junto à metatarsofalângica do II dedo", "5758"),
    ("capsuloligmtf1", "Espessamento capsuloligamentar medial na I metatarsofalângica", "5999"),
    ("fxmtt5", "Fratura oblíqua da região metadiafisária do V metatarso", "5728"),
    ("sequelafxmtt5", "Deformidade da base do V metatarsal por sequela de fratura", "8870"),
    ("fxestressemtt1", "Fratura por estresse incompleta do II metatarsal", "5689"),
    ("fxestressemtt2", "Fratura transversa da diáfise do IV metatarso", "5941", "bullet"),
    ("fxestressemtt3", "Fratura por estresse da metáfise proximal do II metatarso", "5942", "bullet"),
    ("fxestressemtt4", "Fratura por estresse da diáfise distal do II metatarsal", "5943", "bullet"),
    ("periostitemtt1", "Periostite do II metatarso com formação de calo ósseo", "1020"),
    ("edemamtt1", "Edema ósseo nas cabeças do IV e V metatarsos", "5950"),
    ("edemamtt2", "Edema inespecífico do III metatarsal — reação de estresse", "6036"),
    ("cistomtt1", "Formação cística intraóssea do IV metatarsal", "6037"),
    ("contusaomediope1", "Edema pós-contusional das bases dos metatarsos e tarso", "5692"),

    # ---- espaços intermetatársicos e coxim plantar ----
    ("neuromamort1", "Imagens sugestivas de neuroma de Morton", "5623"),
    ("neuromamort2", "Neuroma de Morton no III espaço intermetatarsal", "5734"),
    ("neuromamort3", "Pequeno neuroma interdigital no III interespaço", "5735"),
    ("neuromamort4", "Esboços nodulares no II e III espaços — pequenos neuromas", "5736"),
    ("neuromamort5", "Mínima obliteração da gordura perineural sem nódulo", "5737"),
    ("neuromamort6", "Fibrose perineural inicial sem configuração nodular", "5738"),
    ("neuromamort7", "Obliteração perineural com bursite do III espaço", "5739"),
    ("neuromamort8", "Obliteração da gordura perineural — pequenos neuromas de Morton", "6042"),
    ("neuromamort9", "Nódulo do II espaço intermetatarsal sugestivo de Morton", "8871"),
    ("bursaintermet1", "Pequena bursite intermetatarsal", "5626"),
    ("bursaintermet3", "Mínima bursite no III espaço intermetatársico", "5743"),
    ("bursaintermet4", "Distensão líquida da bursa intermetatársica do II espaço", "5744"),
    ("bursaintermet5", "Distensão das bursas intermetatársicas do II e III espaços", "6041"),
    ("bursaintermet6", "Distensão líquida da bursa do I espaço intermetatarsal", "8872"),
    ("coxim1", "Obliteração por calosidade do coxim gorduroso plantar", "5754"),
    ("coxim2", "Obliteração da gordura plantar sob as cabeças do I e V metatarsos", "5757"),
    ("coxim3", "Obliteração do coxim plantar com realce — bursite adventícia", "6043"),
    ("bursaadvent1", "Bursite reacional plantar por extensão do processo inflamatório", "5953"),
    ("fibromatplant1", "Fibromatose plantar — espessamento fusiforme da banda central", "5751"),
    ("fibromatplant2", "Fibromatose plantar — espessamento nodular com realce", "5934"),

    # ---- neuropatia, infecção e artropatia neuropática ----
    ("charcotpe1", "Artropatia neuropática (Charcot) do mediopé", "5813"),
    ("charcotpe2", "Afilamento condral difuso com fragmentação — artropatia neuropática", "5816"),
    ("charcotpe3", "TC — anquilose do tarso com erosões (artropatia de Charcot)", "8831", "bullet"),
    ("artroneuropat1", "Artropatia do mediopé — degenerativa x inflamatória x neuropática", "5696"),
    ("artroneuropat2", "Atrofia interóssea com subluxação dorsal — artropatia neuropática", "5969"),
    ("denervpe1", "Atrofia e lipossubstituição da musculatura intrínseca do pé", "5775"),
    ("denervpe2", "Atrofia difusa do médio e antepé por neuropatia diabética", "5922"),
    ("denervplantar1", "Atrofia da musculatura plantar lateral e abdutor do V dedo", "8435"),
    ("osteomielitepe1", "Osteomielite e pioartrite do mediopé com Charcot de base", "5838"),
    ("osteomielitepe2", "Osteomielite do cuboide com erosão cortical", "5877"),
    ("osteomielitepe3", "Processo infeccioso inicial junto à cabeça do II metatarso", "5882"),
    ("osteomielhalux1", "Osteomielite da falange proximal do hálux", "5967"),
    ("pioartritemtf1", "Pioartrite e osteomielite da II metatarsofalângica", "5903"),
    ("maduromicose1", "Lesão nodular do antepé — maduromicose", "5979"),
    ("trombosetibpost1", "Alteração inflamatória do feixe vásculo-neural do tibial posterior", "5930"),
    ("gotape1", "TC — erosões subcorticais das cabeças metatarsais (gota)", "8834", "bullet"),
    ("gotape2", "TC — tofos gotosos nos recessos sinoviais", "8835", "bullet"),
    ("gotape3", "TC — erosões em saca-bocado nas metatarsofalângicas", "8836", "bullet"),
    ("gotape4", "Gota tofácea — erosões tarsometatarsais com tofos", "12067"),
    ("gotape5", "Tofo com componente cístico na transição médio/antepé", "12068"),
    ("posoptornozelo1", "Manipulação cirúrgica com osteotomia do calcâneo", "8816", "bullet"),

    ("gotape6", "Conclusão — gota tofácea com componente cístico", "12075"),
    ("gotape7", "TC — erosões na base dos metatarsais e ossos do tarso", "8837", "bullet"),
    ("gotape8", "Demais articulações regulares, sem derrame articular", "12069", "bullet"),
    ("miotendinpenl1", "Demais planos musculares e tendíneos sem anormalidades", "852"),
    ("condralpenl1", "Superfícies condrais preservadas", "849"),
    ("sindactilia1", "Fusão da pele e planos mioadiposos do quarto e quinto dedos", "5805"),
    ("colecaonl1", "TC — não há evidências de coleções (abscessos)", "10663"),
    # ---- laudos completos ----
    ("rmtornozelo", "RM de tornozelo — normal", "8380-8426"),
    ("rmtornozelo2", "RM de tornozelo — pé plano com fasciíte plantar", "8440-8470"),
    ("rmtornozelo3", "RM de tornozelo — modelo mestre com todas as variantes", "8497-8808 !8516,8531,8547,8576,8597,8616,8628,8632,8647,8667,8683,8701,8716,8742,8763,8768,8790"),
    ("rmtornozelo4", "RM de pés e tornozelos — pé plano com tendinopatia do tibial posterior", "8853-8879"),
    ("rmtornozelo5", "RM de tornozelo — modelo mestre com alternativas (Relatório/I.D.)", "8899-8924"),
    ("rmtornozelo6", "RM de tornozelo — síndrome de Haglund (modelo Relatório/I.D.)", "8931-8956"),
    ("rmtornozelo7", "RM de tornozelo — lesão do talofibular anterior (modelo Relatório/I.D.)", "8962-8987"),
    ("rmtornozelo8", "RM de tornozelo — anquilose com rotura do tibial posterior", "11950-11969"),
    ("rmtornozelo9", "RM de tornozelo — entorse do mediopé", "12321-12346"),
    ("rmtornozelo10", "RM de tornozelo — tendinopatias e fasciíte plantar", "12442-12463"),
    ("rmtornozelo11", "RM de tornozelo — rotura do deltoide e do retináculo dos flexores", "12259-12284"),
    ("rmtornozelo12", "RM de tornozelo — artrose com impacto subfibular", "8882-8895"),
    ("rmpe2", "RM de pé — modelo mestre com alternativas", "5584-5643"),
    ("rmpe3", "RM de pé — modelo mestre com todas as variantes", "5647-5790 !5695,5750"),
    ("rmpe4", "RM de pé — osteomielite com artropatia de Charcot", "5833-5852"),
    ("rmpe5", "RM de antepé — bursite intermetatársica e sobrecarga do coxim", "5991-6002"),
    ("rmpe6", "RM de retropé — fasciíte plantar e tendinopatia do calcâneo", "6004-6027"),
    ("rmpe7", "RM dos antepés — hálux valgo, neuromas e sinovite", "6029-6055"),
    ("rmpe8", "RM de antepé — úlcera plantar com osteíte do hálux", "1-23"),
    ("tctornozelo", "TC de tornozelo — lipoma intraósseo do calcâneo", "10712-10755"),
    ("tctornozelo2", "TC de tornozelo — pós-operatório de barra óssea", "10761-10769"),
    ("tctornozelo3", "TC de tornozelo — barra óssea talocalcaneana", "10795-10802"),
    ("tctornozelo4", "TC de pé e tornozelo — controle pós-osteossíntese", "11127-11158"),
    ("tcpe2", "TC dos pés — coalizão calcaneonavicular", "10529-10547"),
    ("rmtornozelo13", "RM de tornozelo — lesão crônica dos ligamentos laterais", "548-583"),
    ("rmtornozelo14", "RM de tornozelo — lesão pregressa dos laterais com split do fibular", "12515-12535"),
    ("tctibia", "TC de tíbia — osteossíntese com consolidação parcial", "12548-12564"),
]
