# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:

  - trigger: "redd"
    word: true
    replace: "site:reddit.com"
    
  - trigger: "codc"
    replace: Correlacionar com dados clínicos.
    word: true

  - trigger: "colab"
    replace: Correlacionar com dados clínicos e laboratoriais.
    word: true

  - trigger: "cocx"
    replace: Correlacionar com histórico cirúrgico.
    word: true

  - trigger: "acrirm"
    replace: A critério clínico, o estudo dirigido com ressonância magnética poderá trazer maiores subsídios diagnósticos.
    word: true

  - trigger: "acritc"
    replace: A critério clínico, o estudo dirigido com tomografia computadorizada poderá trazer maiores subsídios diagnósticos.
    word: true

  - trigger: "acri1"
    replace: A critério clínico, o estudo dirigido da região poderá trazer maiores subsídios diagnósticos.
    word: true

  - trigger: "rest"
    replace: Restante do 
    word: true

  - trigger: "hx0"
    replace: "Indicação clínica: não informada no pedido médico."
    word: true

  - trigger: "hx"
    replace: "Indicação clínica: "
    word: true

  - trigger: "a/e"
    replace: a esclarecer
    word: true

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
